import { EvmChainId } from '../../../chain/evm/index.js'
import type { FuroChainId } from '../../features/furo.js'
import {
  CORE_HOST,
  DECENTRALIZED_HOST_BY_DEPLOYMENT_ID,
  HAQQ_HOST,
  SUSHI_DEDICATED_GOLDSKY_HOST,
  THUNDERCORE_HOST,
} from '../hosts.js'

export const FURO_SUBGRAPH_URL: Record<FuroChainId, string> = {
  [EvmChainId.ETHEREUM]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmQLU8dEJcxYj7rVGbGWRYHrhKifbQKTtPRfKhHw1aszWh`,
  [EvmChainId.ARBITRUM]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmQV6TaRFgBdk4ykzpf6mfdWVB2GLVjkidJZ2YWctR2w2C`,
  [EvmChainId.AVALANCHE]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmbBFHznvVVj5FHA32nHCJ3EEbGBFV7gbnEJ7MvcfJSWRg`,
  [EvmChainId.BSC]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmVQ9jq4bBgfGKzKBL1AjYFGTqLEAYqTPUbs9YienYewpf`,
  [EvmChainId.FANTOM]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmUCx4QRvmDiP1fJaE8RQ72YkkXP9c62rckyhf9EPh87aj`,
  [EvmChainId.GNOSIS]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/Qmf7PkcBd251aKyxCcMPRBWKc76tZ8k1xmVMSZ5zKqoSbh`,
  [EvmChainId.HARMONY]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/Qma2FYbCR7iBQmGaGN4oLMB5TtnBcN9bgTttYyt3vD6xXX`,
  [EvmChainId.MOONBEAM]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmNwmGQw2vcK991B7MJCJgsZAS8Mt2fQZ41qrPMJFVKaAU`,
  [EvmChainId.MOONRIVER]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmdChdTYcr6YgfKHw6FCUtJsfZBEQkvsoAkiRAs1GcGWMZ`,
  [EvmChainId.OPTIMISM]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmajmWiw8tyhgJcGk69QiL2gEXqniM3PNPAaLjPh6dYfpf`,
  [EvmChainId.POLYGON]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmT25bz8HV5173wbZ21vcMR76R34BW7Bix4fES9iibBKKW`,
  [EvmChainId.HAQQ]: `${HAQQ_HOST}/sushi/furo-haqq`,
  [EvmChainId.CORE]: `${CORE_HOST}/sushi-subgraphs/furo-core`,
  [EvmChainId.THUNDERCORE]: `${THUNDERCORE_HOST}/sushi-subgraphs/furo-thundercore`,
  [EvmChainId.BTTC]: `${SUSHI_DEDICATED_GOLDSKY_HOST}/sushi-subgraphs/furo-bttc/gn`,
}
