import { EvmChainId } from '../../../chain/evm/index.js'
import type { MiniChefChainId } from '../../features/mini-chef.js'
import {
  DECENTRALIZED_HOST_BY_DEPLOYMENT_ID,
  METIS_0XGRAPH_HOST,
  SUSHI_DEDICATED_GOLDSKY_HOST,
} from '../hosts.js'

export const MINICHEF_SUBGRAPH_URL: Record<MiniChefChainId, string> = {
  [EvmChainId.POLYGON]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmRGvRxvfNgVNU9QcTDj6XpASfA3HaYCGJiKqRmthGdjm2`,
  [EvmChainId.GNOSIS]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmRjFd4SPZDpMdjkPQqgN9v4trWXpQoqikFrmqpBUMiTJY`,
  // [EvmChainId.HARMONY]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/xx`,// NO FIX has been deployed yet
  [EvmChainId.ARBITRUM]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmbcWZNLLCSmuQ474rYr4jCymN22jguT9hZtp4rZzA3T2w`,
  [EvmChainId.CELO]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmPpECMB4vnHe2SpkLQCFp7dumWfXUekhZBbfVAEM64BjS`,
  [EvmChainId.MOONRIVER]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmaZo8AP9HQPXrnVUP1outjfsb3xJW1PF9X6UHjzid1aYH`,
  [EvmChainId.FUSE]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmauqkgAJTjwfKDAvtY4siuPZF2oczg6jqWC9wMqw21yQH`,
  [EvmChainId.FANTOM]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmajRCaeDeftPiNKndmqCRMknKLNC6sFXBREWX4HHyfzv8`,
  [EvmChainId.MOONBEAM]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmVeQLQJzy1T21UtKncpLs8nNjRczKz5sUT94h515QhwuJ`,
  [EvmChainId.BOBA]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmZdYzMxLNHM5u8YjhoMdQUfNHDC4KxwBVAB3XAk9WSaui`,
  [EvmChainId.OPTIMISM]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmcTYTs3DCbxF97gyo1tq54Vkd9YUDcSjPNUB1rRKBotrM`,
  [EvmChainId.AVALANCHE]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmamfQF1cQMWgYVWM7vYq1yTL5fTrkr2ZYCAYR9rMsEWV5`,
  [EvmChainId.BSC]: `${DECENTRALIZED_HOST_BY_DEPLOYMENT_ID}/QmfFsgEPtw6mCkaaLxk2e52E7G2KryTzn6R1eTYoL3Mj1c`,
  [EvmChainId.KAVA]: `${SUSHI_DEDICATED_GOLDSKY_HOST}/sushiswap/minichef-kava/gn`,
  [EvmChainId.METIS]: `${METIS_0XGRAPH_HOST}/sushiswap/minichef-metis`,
  [EvmChainId.ARBITRUM_NOVA]: `${SUSHI_DEDICATED_GOLDSKY_HOST}/sushiswap/minichef-arbitrum-nova/gn`,
  [EvmChainId.BTTC]: `${SUSHI_DEDICATED_GOLDSKY_HOST}/sushiswap/minichef-bttc/gn`,
}
