import { EvmChainId } from '../../chain/evm/index.js'
import {
  BUSD,
  BUSD_ADDRESS,
  DAI,
  DAI_ADDRESS,
  FRAX,
  FRAX_ADDRESS,
  MAI,
  MAI_ADDRESS,
  Token,
  type Type,
  USDC,
  USDC_ADDRESS,
  USDT,
  USDT_ADDRESS,
} from '../../currency/index.js'

export const STARGATE_CHAIN_ID = {
  [EvmChainId.ETHEREUM]: 101,
  [EvmChainId.BSC]: 102,
  [EvmChainId.AVALANCHE]: 106,
  [EvmChainId.POLYGON]: 109,
  [EvmChainId.ARBITRUM]: 110,
  [EvmChainId.OPTIMISM]: 111,
  [EvmChainId.FANTOM]: 112,
  [EvmChainId.METIS]: 151,
  [EvmChainId.BASE]: 184,
  [EvmChainId.LINEA]: 183,
  [EvmChainId.KAVA]: 177,
} as const

export const STARGATE_WIDGET_ADDRESS = {
  [EvmChainId.ETHEREUM]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
  [EvmChainId.BSC]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
  [EvmChainId.AVALANCHE]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
  [EvmChainId.ARBITRUM]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
  [EvmChainId.POLYGON]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
  [EvmChainId.OPTIMISM]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
  [EvmChainId.FANTOM]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
  [EvmChainId.METIS]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
  [EvmChainId.BASE]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
  [EvmChainId.LINEA]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
  [EvmChainId.KAVA]: '0x10d16248bED1E0D0c7cF94fFD99A50c336c7Bcdc',
} as const

export const STARGATE_COMPOSER_ADDRESS = {
  [EvmChainId.ETHEREUM]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
  [EvmChainId.BSC]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
  [EvmChainId.AVALANCHE]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
  [EvmChainId.ARBITRUM]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
  [EvmChainId.POLYGON]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
  [EvmChainId.OPTIMISM]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
  [EvmChainId.FANTOM]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
  [EvmChainId.METIS]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
  [EvmChainId.BASE]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
  [EvmChainId.LINEA]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
  [EvmChainId.KAVA]: '0xeCc19E177d24551aA7ed6Bc6FE566eCa726CC8a9',
} as const

export const STARGATE_ETH_ADDRESS = {
  [EvmChainId.ETHEREUM]: '0x72E2F4830b9E45d52F80aC08CB2bEC0FeF72eD9c',
  [EvmChainId.ARBITRUM]: '0x82CbeCF39bEe528B5476FE6d1550af59a9dB6Fc0',
  [EvmChainId.OPTIMISM]: '0xb69c8CBCD90A39D8D3d3ccf0a3E968511C3856A0',
  [EvmChainId.BASE]: '0x224d8fd7ab6ad4c6eb4611ce56ef35dec2277f03',
  [EvmChainId.LINEA]: '0x224d8fd7ab6ad4c6eb4611ce56ef35dec2277f03',
} as const

export const STARGATE_ETH: Record<keyof typeof STARGATE_ETH_ADDRESS, Token> = {
  [EvmChainId.ETHEREUM]: new Token({
    chainId: EvmChainId.ETHEREUM,
    address: STARGATE_ETH_ADDRESS[EvmChainId.ETHEREUM],
    decimals: 18,
    symbol: 'SGETH',
    name: 'Stargate Ether',
  }),
  [EvmChainId.ARBITRUM]: new Token({
    chainId: EvmChainId.ARBITRUM,
    address: STARGATE_ETH_ADDRESS[EvmChainId.ARBITRUM],
    decimals: 18,
    symbol: 'SGETH',
    name: 'Stargate Ether',
  }),
  [EvmChainId.OPTIMISM]: new Token({
    chainId: EvmChainId.OPTIMISM,
    address: STARGATE_ETH_ADDRESS[EvmChainId.OPTIMISM],
    decimals: 18,
    symbol: 'SGETH',
    name: 'Stargate Ether',
  }),
  [EvmChainId.BASE]: new Token({
    chainId: EvmChainId.BASE,
    address: STARGATE_ETH_ADDRESS[EvmChainId.BASE],
    decimals: 18,
    symbol: 'SGETH',
    name: 'Stargate Ether',
  }),
  [EvmChainId.LINEA]: new Token({
    chainId: EvmChainId.LINEA,
    address: STARGATE_ETH_ADDRESS[EvmChainId.LINEA],
    decimals: 18,
    symbol: 'SGETH',
    name: 'Stargate Ether',
  }),
}

export const STARGATE_WETH_ADDRESS = {
  [EvmChainId.FANTOM]: '0x695921034f0387eAc4e11620EE91b1b15A6A09fE',
  [EvmChainId.KAVA]: '0x2DfD4dE5AE386Cd3f4fC8e2cb39240852E47F5E8',
}

export const STARGATE_WETH = {
  [EvmChainId.FANTOM]: new Token({
    chainId: EvmChainId.FANTOM,
    address: STARGATE_WETH_ADDRESS[EvmChainId.FANTOM],
    decimals: 18,
    symbol: 'WETH',
    name: 'Wrapped Ether',
  }),
  [EvmChainId.KAVA]: new Token({
    chainId: EvmChainId.KAVA,
    address: STARGATE_WETH_ADDRESS[EvmChainId.KAVA],
    decimals: 18,
    symbol: 'WETH',
    name: 'Wrapped Ether',
  }),
}

export const STARGATE_WBTC_ADDRESS = {
  [EvmChainId.FANTOM]: '0xf1648C50d2863f780c57849D812b4B7686031A3D',
}

export const STARGATE_WBTC = {
  [EvmChainId.FANTOM]: new Token({
    chainId: EvmChainId.FANTOM,
    address: STARGATE_WBTC_ADDRESS[EvmChainId.FANTOM],
    decimals: 18,
    symbol: 'WBTC',
    name: 'Wrapped BTC',
  }),
}

export const STARGATE_USDC_ADDRESS = {
  [EvmChainId.ETHEREUM]: USDC_ADDRESS[EvmChainId.ETHEREUM],
  [EvmChainId.AVALANCHE]: USDC_ADDRESS[EvmChainId.AVALANCHE],
  [EvmChainId.POLYGON]: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174',
  [EvmChainId.ARBITRUM]: '0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8',
  [EvmChainId.OPTIMISM]: '0x7F5c764cBc14f9669B88837ca1490cCa17c31607',
  // [EvmChainId.FANTOM]: USDC_ADDRESS[EvmChainId.FANTOM],
  [EvmChainId.FANTOM]: '0x28a92dde19D9989F39A49905d7C9C2FAc7799bDf',
  // [EvmChainId.BASE]: USDC_ADDRESS[EvmChainId.BASE],
  [EvmChainId.BASE]: '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA',
} as const

export const STARGATE_USDC: Record<keyof typeof STARGATE_USDC_ADDRESS, Token> =
  {
    [EvmChainId.ETHEREUM]: USDC[EvmChainId.ETHEREUM],
    [EvmChainId.AVALANCHE]: USDC[EvmChainId.AVALANCHE],
    [EvmChainId.POLYGON]: new Token({
      chainId: EvmChainId.POLYGON,
      address: STARGATE_USDC_ADDRESS[EvmChainId.POLYGON],
      decimals: 6,
      symbol: 'USDC',
      name: 'USD Coin',
    }),
    [EvmChainId.ARBITRUM]: new Token({
      chainId: EvmChainId.ARBITRUM,
      address: STARGATE_USDC_ADDRESS[EvmChainId.ARBITRUM],
      decimals: 6,
      symbol: 'USDC',
      name: 'USD Coin',
    }),
    [EvmChainId.OPTIMISM]: new Token({
      chainId: EvmChainId.OPTIMISM,
      address: STARGATE_USDC_ADDRESS[EvmChainId.OPTIMISM],
      decimals: 6,
      symbol: 'USDC',
      name: 'USD Coin',
    }),
    // [EvmChainId.FANTOM]: USDC[EvmChainId.FANTOM],
    [EvmChainId.FANTOM]: new Token({
      chainId: EvmChainId.FANTOM,
      address: STARGATE_USDC_ADDRESS[EvmChainId.FANTOM],
      decimals: 6,
      symbol: 'USDC',
      name: 'USD Coin',
    }),
    // [EvmChainId.BASE]: USDC[EvmChainId.BASE],
    [EvmChainId.BASE]: new Token({
      chainId: EvmChainId.BASE,
      address: STARGATE_USDC_ADDRESS[EvmChainId.BASE],
      decimals: 6,
      symbol: 'USDC',
      name: 'USD Coin',
    }),
  } as const

export const STARGATE_USDT_ADDRESS = {
  [EvmChainId.ETHEREUM]: USDT_ADDRESS[EvmChainId.ETHEREUM],
  [EvmChainId.BSC]: USDT_ADDRESS[EvmChainId.BSC],
  [EvmChainId.AVALANCHE]: USDT_ADDRESS[EvmChainId.AVALANCHE],
  [EvmChainId.POLYGON]: USDT_ADDRESS[EvmChainId.POLYGON],
  [EvmChainId.ARBITRUM]: USDT_ADDRESS[EvmChainId.ARBITRUM],
  [EvmChainId.FANTOM]: '0xcc1b99dDAc1a33c201a742A1851662E87BC7f22C',
  [EvmChainId.METIS]: USDT_ADDRESS[EvmChainId.METIS],
  [EvmChainId.KAVA]: '0xAad094F6A75A14417d39f04E690fC216f080A41a',
} as const

export const STARGATE_USDT: Record<keyof typeof STARGATE_USDT_ADDRESS, Token> =
  {
    [EvmChainId.ETHEREUM]: USDT[EvmChainId.ETHEREUM],
    [EvmChainId.BSC]: USDT[EvmChainId.BSC],
    [EvmChainId.AVALANCHE]: USDT[EvmChainId.AVALANCHE],
    [EvmChainId.POLYGON]: USDT[EvmChainId.POLYGON],
    [EvmChainId.ARBITRUM]: USDT[EvmChainId.ARBITRUM],
    [EvmChainId.FANTOM]: new Token({
      chainId: EvmChainId.FANTOM,
      address: STARGATE_USDT_ADDRESS[EvmChainId.FANTOM],
      decimals: 6,
      symbol: 'USDT',
      name: 'Tether USD',
    }),
    [EvmChainId.METIS]: USDT[EvmChainId.METIS],
    [EvmChainId.KAVA]: new Token({
      chainId: EvmChainId.KAVA,
      address: STARGATE_USDT_ADDRESS[EvmChainId.KAVA],
      decimals: 6,
      symbol: 'USDT',
      name: 'Tether USD',
    }),
  } as const

export const STARGATE_DAI_ADDRESS = {
  [EvmChainId.ETHEREUM]: DAI_ADDRESS[EvmChainId.ETHEREUM],
  [EvmChainId.POLYGON]: DAI_ADDRESS[EvmChainId.POLYGON],
  [EvmChainId.OPTIMISM]: DAI_ADDRESS[EvmChainId.OPTIMISM],
} as const

export const STARGATE_DAI: Record<keyof typeof STARGATE_DAI_ADDRESS, Token> = {
  [EvmChainId.ETHEREUM]: DAI[EvmChainId.ETHEREUM],
  [EvmChainId.POLYGON]: DAI[EvmChainId.POLYGON],
  [EvmChainId.OPTIMISM]: DAI[EvmChainId.OPTIMISM],
} as const

export const STARGATE_FRAX_ADDRESS = {
  [EvmChainId.ETHEREUM]: FRAX_ADDRESS[EvmChainId.ETHEREUM],
  [EvmChainId.AVALANCHE]: FRAX_ADDRESS[EvmChainId.AVALANCHE],
  [EvmChainId.ARBITRUM]: FRAX_ADDRESS[EvmChainId.ARBITRUM],
  [EvmChainId.OPTIMISM]: FRAX_ADDRESS[EvmChainId.OPTIMISM],
} as const

export const STARGATE_FRAX: Record<keyof typeof STARGATE_FRAX_ADDRESS, Token> =
  {
    [EvmChainId.ETHEREUM]: FRAX[EvmChainId.ETHEREUM],
    [EvmChainId.AVALANCHE]: FRAX[EvmChainId.AVALANCHE],
    [EvmChainId.ARBITRUM]: FRAX[EvmChainId.ARBITRUM],
    [EvmChainId.OPTIMISM]: FRAX[EvmChainId.OPTIMISM],
  }

export const STARGATE_BUSD_ADDRESS = {
  [EvmChainId.BSC]: BUSD_ADDRESS[EvmChainId.BSC],
} as const

export const STARGATE_BUSD: Record<keyof typeof STARGATE_BUSD_ADDRESS, Token> =
  {
    [EvmChainId.BSC]: BUSD[EvmChainId.BSC],
  }

export const STARGATE_MAI_ADDRESS = {
  [EvmChainId.ETHEREUM]: MAI_ADDRESS[EvmChainId.ETHEREUM],
  [EvmChainId.BSC]: MAI_ADDRESS[EvmChainId.BSC],
  [EvmChainId.AVALANCHE]: MAI_ADDRESS[EvmChainId.AVALANCHE],
  [EvmChainId.POLYGON]: MAI_ADDRESS[EvmChainId.POLYGON],
  [EvmChainId.ARBITRUM]: MAI_ADDRESS[EvmChainId.ARBITRUM],
  [EvmChainId.OPTIMISM]: MAI_ADDRESS[EvmChainId.OPTIMISM],
} as const

export const STARGATE_MAI: Record<keyof typeof STARGATE_MAI_ADDRESS, Token> = {
  [EvmChainId.ETHEREUM]: MAI[EvmChainId.ETHEREUM],
  [EvmChainId.BSC]: MAI[EvmChainId.BSC],
  [EvmChainId.AVALANCHE]: MAI[EvmChainId.AVALANCHE],
  [EvmChainId.POLYGON]: MAI[EvmChainId.POLYGON],
  [EvmChainId.ARBITRUM]: MAI[EvmChainId.ARBITRUM],
  [EvmChainId.OPTIMISM]: MAI[EvmChainId.OPTIMISM],
}

export const STARGATE_BRIDGE_TOKENS: Record<number, Token[]> = {
  [EvmChainId.ETHEREUM]: [
    STARGATE_ETH[EvmChainId.ETHEREUM],
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_DAI[EvmChainId.ETHEREUM],
    STARGATE_FRAX[EvmChainId.ETHEREUM],
    STARGATE_MAI[EvmChainId.ETHEREUM],
  ],
  [EvmChainId.BSC]: [
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_BUSD[EvmChainId.BSC],
    STARGATE_MAI[EvmChainId.BSC],
  ],
  [EvmChainId.AVALANCHE]: [
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_FRAX[EvmChainId.AVALANCHE],
    STARGATE_MAI[EvmChainId.AVALANCHE],
  ],
  [EvmChainId.POLYGON]: [
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_DAI[EvmChainId.POLYGON],
    STARGATE_MAI[EvmChainId.POLYGON],
  ],
  [EvmChainId.ARBITRUM]: [
    STARGATE_ETH[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_FRAX[EvmChainId.ARBITRUM],
    STARGATE_MAI[EvmChainId.ARBITRUM],
  ],
  [EvmChainId.OPTIMISM]: [
    STARGATE_ETH[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_DAI[EvmChainId.OPTIMISM],
    STARGATE_FRAX[EvmChainId.OPTIMISM],
    STARGATE_MAI[EvmChainId.OPTIMISM],
  ],
  [EvmChainId.FANTOM]: [STARGATE_USDC[EvmChainId.FANTOM]],
  [EvmChainId.METIS]: [STARGATE_USDT[EvmChainId.METIS]],
  [EvmChainId.BASE]: [
    STARGATE_ETH[EvmChainId.BASE],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [EvmChainId.LINEA]: [STARGATE_ETH[EvmChainId.LINEA]],
}

export const STARGATE_BRIDGE_TOKEN_ADDRESSES: Record<number, string[]> = {
  [EvmChainId.ETHEREUM]: [
    STARGATE_ETH_ADDRESS[EvmChainId.ETHEREUM],
    STARGATE_USDC_ADDRESS[EvmChainId.ETHEREUM],
    STARGATE_USDT_ADDRESS[EvmChainId.ETHEREUM],
    STARGATE_DAI_ADDRESS[EvmChainId.ETHEREUM],
    STARGATE_FRAX_ADDRESS[EvmChainId.ETHEREUM],
    STARGATE_MAI_ADDRESS[EvmChainId.ETHEREUM],
  ],
  [EvmChainId.BSC]: [
    STARGATE_USDT_ADDRESS[EvmChainId.BSC],
    STARGATE_BUSD_ADDRESS[EvmChainId.BSC],
    STARGATE_MAI_ADDRESS[EvmChainId.BSC],
  ],
  [EvmChainId.AVALANCHE]: [
    STARGATE_USDC_ADDRESS[EvmChainId.AVALANCHE],
    STARGATE_USDT_ADDRESS[EvmChainId.AVALANCHE],
    STARGATE_FRAX_ADDRESS[EvmChainId.AVALANCHE],
    STARGATE_MAI_ADDRESS[EvmChainId.AVALANCHE],
  ],
  [EvmChainId.POLYGON]: [
    STARGATE_USDC_ADDRESS[EvmChainId.POLYGON],
    STARGATE_USDT_ADDRESS[EvmChainId.POLYGON],
    STARGATE_DAI_ADDRESS[EvmChainId.POLYGON],
    STARGATE_MAI_ADDRESS[EvmChainId.POLYGON],
  ],
  [EvmChainId.ARBITRUM]: [
    STARGATE_ETH_ADDRESS[EvmChainId.ARBITRUM],
    STARGATE_USDC_ADDRESS[EvmChainId.ARBITRUM],
    STARGATE_USDT_ADDRESS[EvmChainId.ARBITRUM],
    STARGATE_FRAX_ADDRESS[EvmChainId.ARBITRUM],
    STARGATE_MAI_ADDRESS[EvmChainId.ARBITRUM],
  ],
  [EvmChainId.OPTIMISM]: [
    STARGATE_ETH_ADDRESS[EvmChainId.OPTIMISM],
    STARGATE_USDC_ADDRESS[EvmChainId.OPTIMISM],
    STARGATE_DAI_ADDRESS[EvmChainId.OPTIMISM],
    STARGATE_FRAX_ADDRESS[EvmChainId.OPTIMISM],
    STARGATE_MAI_ADDRESS[EvmChainId.OPTIMISM],
  ],
  [EvmChainId.FANTOM]: [STARGATE_USDC_ADDRESS[EvmChainId.FANTOM]],
  [EvmChainId.METIS]: [STARGATE_USDT_ADDRESS[EvmChainId.METIS]],
  [EvmChainId.BASE]: [
    STARGATE_ETH_ADDRESS[EvmChainId.BASE],
    STARGATE_USDC_ADDRESS[EvmChainId.BASE],
  ],
  [EvmChainId.LINEA]: [STARGATE_ETH_ADDRESS[EvmChainId.LINEA]],
}

export const STARGATE_POOL_ID: Record<number, Record<string, number>> = {
  [EvmChainId.ETHEREUM]: {
    [STARGATE_ETH_ADDRESS[EvmChainId.ETHEREUM]]: 13,
    [STARGATE_USDC_ADDRESS[EvmChainId.ETHEREUM]]: 1,
    [STARGATE_USDT_ADDRESS[EvmChainId.ETHEREUM]]: 2,
    [STARGATE_DAI_ADDRESS[EvmChainId.ETHEREUM]]: 3,
    [STARGATE_FRAX_ADDRESS[EvmChainId.ETHEREUM]]: 7,
    [STARGATE_MAI_ADDRESS[EvmChainId.ETHEREUM]]: 16,
  },
  [EvmChainId.BSC]: {
    [STARGATE_USDT_ADDRESS[EvmChainId.BSC]]: 2,
    [STARGATE_BUSD_ADDRESS[EvmChainId.BSC]]: 5,
    [STARGATE_MAI_ADDRESS[EvmChainId.BSC]]: 16,
  },
  [EvmChainId.AVALANCHE]: {
    [STARGATE_USDC_ADDRESS[EvmChainId.AVALANCHE]]: 1,
    [STARGATE_USDT_ADDRESS[EvmChainId.AVALANCHE]]: 2,
    [STARGATE_FRAX_ADDRESS[EvmChainId.AVALANCHE]]: 7,
    [STARGATE_MAI_ADDRESS[EvmChainId.AVALANCHE]]: 16,
  },
  [EvmChainId.POLYGON]: {
    [STARGATE_USDC_ADDRESS[EvmChainId.POLYGON]]: 1,
    [STARGATE_USDT_ADDRESS[EvmChainId.POLYGON]]: 2,
    [STARGATE_DAI_ADDRESS[EvmChainId.POLYGON]]: 3,
    [STARGATE_MAI_ADDRESS[EvmChainId.POLYGON]]: 16,
  },
  [EvmChainId.ARBITRUM]: {
    [STARGATE_ETH_ADDRESS[EvmChainId.ARBITRUM]]: 13,
    [STARGATE_USDC_ADDRESS[EvmChainId.ARBITRUM]]: 1,
    [STARGATE_USDT_ADDRESS[EvmChainId.ARBITRUM]]: 2,
    [STARGATE_FRAX_ADDRESS[EvmChainId.ARBITRUM]]: 7,
    [STARGATE_MAI_ADDRESS[EvmChainId.ARBITRUM]]: 16,
  },
  [EvmChainId.OPTIMISM]: {
    [STARGATE_ETH_ADDRESS[EvmChainId.OPTIMISM]]: 13,
    [STARGATE_USDC_ADDRESS[EvmChainId.OPTIMISM]]: 1,
    [STARGATE_DAI_ADDRESS[EvmChainId.OPTIMISM]]: 3,
    [STARGATE_FRAX_ADDRESS[EvmChainId.OPTIMISM]]: 7,
    [STARGATE_MAI_ADDRESS[EvmChainId.OPTIMISM]]: 16,
  },
  [EvmChainId.FANTOM]: { [STARGATE_USDC_ADDRESS[EvmChainId.FANTOM]]: 21 },
  [EvmChainId.METIS]: { [STARGATE_USDT_ADDRESS[EvmChainId.METIS]]: 19 },
  [EvmChainId.BASE]: {
    [STARGATE_ETH_ADDRESS[EvmChainId.BASE]]: 13,
    [STARGATE_USDC_ADDRESS[EvmChainId.BASE]]: 1,
  },
  [EvmChainId.LINEA]: { [STARGATE_ETH_ADDRESS[EvmChainId.LINEA]]: 13 },
}

export const STARGATE_POOL_ADDRESS: Record<number, Record<string, string>> = {
  [EvmChainId.ETHEREUM]: {
    [STARGATE_ETH_ADDRESS[EvmChainId.ETHEREUM]]:
      '0x101816545F6bd2b1076434B54383a1E633390A2E',
    [STARGATE_USDC_ADDRESS[EvmChainId.ETHEREUM]]:
      '0xdf0770dF86a8034b3EFEf0A1Bb3c889B8332FF56',
    [STARGATE_USDT_ADDRESS[EvmChainId.ETHEREUM]]:
      '0x38ea452219524bb87e18de1c24d3bb59510bd783',
    [STARGATE_DAI_ADDRESS[EvmChainId.ETHEREUM]]:
      '0x0Faf1d2d3CED330824de3B8200fc8dc6E397850d',
    [STARGATE_FRAX_ADDRESS[EvmChainId.ETHEREUM]]:
      '0xfA0F307783AC21C39E939ACFF795e27b650F6e68',
    [STARGATE_MAI_ADDRESS[EvmChainId.ETHEREUM]]:
      '0x9cef9a0b1be0d289ac9f4a98ff317c33eaa84eb8',
  },
  [EvmChainId.BSC]: {
    [STARGATE_USDT_ADDRESS[EvmChainId.BSC]]:
      '0x9aA83081AA06AF7208Dcc7A4cB72C94d057D2cda',
    [STARGATE_BUSD_ADDRESS[EvmChainId.BSC]]:
      '0x98a5737749490856b401DB5Dc27F522fC314A4e1',
    [STARGATE_MAI_ADDRESS[EvmChainId.BSC]]:
      '0x7BfD7f2498C4796f10b6C611D9db393D3052510C',
  },
  [EvmChainId.AVALANCHE]: {
    [STARGATE_USDC_ADDRESS[EvmChainId.AVALANCHE]]:
      '0x1205f31718499dBf1fCa446663B532Ef87481fe1',
    [STARGATE_USDT_ADDRESS[EvmChainId.AVALANCHE]]:
      '0x29e38769f23701A2e4A8Ef0492e19dA4604Be62c',
    [STARGATE_FRAX_ADDRESS[EvmChainId.AVALANCHE]]:
      '0x1c272232Df0bb6225dA87f4dEcD9d37c32f63Eea',
    [STARGATE_MAI_ADDRESS[EvmChainId.AVALANCHE]]:
      '0x8736f92646B2542B3e5F3c63590cA7Fe313e283B',
  },
  [EvmChainId.POLYGON]: {
    [STARGATE_USDC_ADDRESS[EvmChainId.POLYGON]]:
      '0x1205f31718499dBf1fCa446663B532Ef87481fe1',
    [STARGATE_USDT_ADDRESS[EvmChainId.POLYGON]]:
      '0x29e38769f23701A2e4A8Ef0492e19dA4604Be62c',
    [STARGATE_DAI_ADDRESS[EvmChainId.POLYGON]]:
      '0x1c272232Df0bb6225dA87f4dEcD9d37c32f63Eea',
    [STARGATE_MAI_ADDRESS[EvmChainId.POLYGON]]:
      '0x8736f92646B2542B3e5F3c63590cA7Fe313e283B',
  },
  [EvmChainId.ARBITRUM]: {
    [STARGATE_ETH_ADDRESS[EvmChainId.ARBITRUM]]:
      '0x915A55e36A01285A14f05dE6e81ED9cE89772f8e',
    [STARGATE_USDC_ADDRESS[EvmChainId.ARBITRUM]]:
      '0x892785f33CdeE22A30AEF750F285E18c18040c3e',
    [STARGATE_USDT_ADDRESS[EvmChainId.ARBITRUM]]:
      '0xB6CfcF89a7B22988bfC96632aC2A9D6daB60d641',
    [STARGATE_FRAX_ADDRESS[EvmChainId.ARBITRUM]]:
      '0xaa4BF442F024820B2C28Cd0FD72b82c63e66F56C',
    [STARGATE_MAI_ADDRESS[EvmChainId.ARBITRUM]]:
      '0xF39B7Be294cB36dE8c510e267B82bb588705d977',
  },
  [EvmChainId.OPTIMISM]: {
    [STARGATE_ETH_ADDRESS[EvmChainId.OPTIMISM]]:
      '0xd22363e3762cA7339569F3d33EADe20127D5F98C',
    [STARGATE_USDC_ADDRESS[EvmChainId.OPTIMISM]]:
      '0xDecC0c09c3B5f6e92EF4184125D5648a66E35298',
    [STARGATE_DAI_ADDRESS[EvmChainId.OPTIMISM]]:
      '0x165137624F1f692e69659f944BF69DE02874ee27',
    [STARGATE_FRAX_ADDRESS[EvmChainId.OPTIMISM]]:
      '0x368605D9C6243A80903b9e326f1Cddde088B8924',
    [STARGATE_MAI_ADDRESS[EvmChainId.OPTIMISM]]:
      '0x5421FA1A48f9FF81e4580557E86C7C0D24C18036',
  },
  [EvmChainId.FANTOM]: {
    [STARGATE_USDC_ADDRESS[EvmChainId.FANTOM]]:
      '0xc647ce76ec30033aa319d472ae9f4462068f2ad7',
  },
  [EvmChainId.METIS]: {
    [STARGATE_USDT_ADDRESS[EvmChainId.METIS]]:
      '0x2b60473a7C41Deb80EDdaafD5560e963440eb632',
  },
  [EvmChainId.BASE]: {
    [STARGATE_ETH_ADDRESS[EvmChainId.BASE]]:
      '0x28fc411f9e1c480AD312b3d9C60c22b965015c6B',
    [STARGATE_USDC_ADDRESS[EvmChainId.BASE]]:
      '0x4c80e24119cfb836cdf0a6b53dc23f04f7e652ca',
  },
  [EvmChainId.LINEA]: {
    [STARGATE_ETH_ADDRESS[EvmChainId.LINEA]]:
      '0xAad094F6A75A14417d39f04E690fC216f080A41a',
  },
}

export function isStargateBridgeToken(currency: Type | undefined) {
  if (!currency) return false
  if (currency.isNative && currency.chainId in STARGATE_ETH_ADDRESS) return true
  if (!STARGATE_BRIDGE_TOKEN_ADDRESSES[currency.chainId]) return false
  return STARGATE_BRIDGE_TOKEN_ADDRESSES?.[currency.chainId]?.includes(
    currency.wrapped.address,
  )
}

export const STARGATE_TOKEN = new Token({
  chainId: EvmChainId.ETHEREUM,
  address: '0xaf5191b0de278c7286d6c7cc6ab6bb8a73ba2cd6',
  decimals: 18,
  symbol: 'STG',
  name: 'StargateToken',
})

export type StargateBridgeTokens =
  (typeof STARGATE_BRIDGE_TOKENS)[StargateChainId]

export type StargateBridgeToken = StargateBridgeTokens[number]

export const STARGATE_SUPPORTED_CHAIN_IDS = [
  EvmChainId.ETHEREUM,
  EvmChainId.BSC,
  EvmChainId.AVALANCHE,
  EvmChainId.POLYGON,
  EvmChainId.ARBITRUM,
  EvmChainId.OPTIMISM,
  // EvmChainId.FANTOM,
  EvmChainId.BASE,
  EvmChainId.LINEA,
] as const

export type StargateChainId = (typeof STARGATE_SUPPORTED_CHAIN_IDS)[number]

// https://stargateprotocol.gitbook.io/stargate/developers/stargate-chain-paths

const ETHEREUM_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[EvmChainId.ETHEREUM]]: [
    STARGATE_BUSD[EvmChainId.BSC],
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_USDT_ADDRESS[EvmChainId.ETHEREUM]]: [
    STARGATE_BUSD[EvmChainId.BSC],
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_DAI_ADDRESS[EvmChainId.ETHEREUM]]: [
    STARGATE_DAI[EvmChainId.POLYGON],
    STARGATE_DAI[EvmChainId.OPTIMISM],
  ],
  [STARGATE_FRAX_ADDRESS[EvmChainId.ETHEREUM]]: [
    STARGATE_FRAX[EvmChainId.AVALANCHE],
    STARGATE_FRAX[EvmChainId.ARBITRUM],
    STARGATE_FRAX[EvmChainId.OPTIMISM],
  ],
  [STARGATE_ETH_ADDRESS[EvmChainId.ETHEREUM]]: [
    STARGATE_ETH[EvmChainId.ARBITRUM],
    STARGATE_ETH[EvmChainId.OPTIMISM],
    STARGATE_ETH[EvmChainId.BASE],
    STARGATE_ETH[EvmChainId.LINEA],
  ],
  [STARGATE_MAI_ADDRESS[EvmChainId.ETHEREUM]]: [
    STARGATE_MAI[EvmChainId.BSC],
    STARGATE_MAI[EvmChainId.AVALANCHE],
    STARGATE_MAI[EvmChainId.POLYGON],
    STARGATE_MAI[EvmChainId.ARBITRUM],
    STARGATE_MAI[EvmChainId.OPTIMISM],
  ],
}

const BSC_CHAIN_PATHS = {
  [STARGATE_BUSD_ADDRESS[EvmChainId.BSC]]: [
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_USDT_ADDRESS[EvmChainId.BSC]]: [
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_MAI_ADDRESS[EvmChainId.BSC]]: [
    STARGATE_MAI[EvmChainId.ETHEREUM],
    STARGATE_MAI[EvmChainId.AVALANCHE],
    STARGATE_MAI[EvmChainId.POLYGON],
    STARGATE_MAI[EvmChainId.ARBITRUM],
    STARGATE_MAI[EvmChainId.OPTIMISM],
  ],
}

const AVALANCE_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[EvmChainId.AVALANCHE]]: [
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_BUSD[EvmChainId.BSC],
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_USDT_ADDRESS[EvmChainId.AVALANCHE]]: [
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_BUSD[EvmChainId.BSC],
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_FRAX_ADDRESS[EvmChainId.AVALANCHE]]: [
    STARGATE_FRAX[EvmChainId.ETHEREUM],
    STARGATE_FRAX[EvmChainId.ARBITRUM],
    STARGATE_FRAX[EvmChainId.OPTIMISM],
  ],
  [STARGATE_MAI_ADDRESS[EvmChainId.AVALANCHE]]: [
    STARGATE_MAI[EvmChainId.ETHEREUM],
    STARGATE_MAI[EvmChainId.BSC],
    STARGATE_MAI[EvmChainId.POLYGON],
    STARGATE_MAI[EvmChainId.ARBITRUM],
    STARGATE_MAI[EvmChainId.OPTIMISM],
  ],
}

const POLYGON_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[EvmChainId.POLYGON]]: [
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_BUSD[EvmChainId.BSC],
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_USDT_ADDRESS[EvmChainId.POLYGON]]: [
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_BUSD[EvmChainId.BSC],
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_DAI_ADDRESS[EvmChainId.POLYGON]]: [
    STARGATE_DAI[EvmChainId.ETHEREUM],
    STARGATE_DAI[EvmChainId.OPTIMISM],
  ],
  [STARGATE_MAI_ADDRESS[EvmChainId.POLYGON]]: [
    STARGATE_MAI[EvmChainId.ETHEREUM],
    STARGATE_MAI[EvmChainId.BSC],
    STARGATE_MAI[EvmChainId.AVALANCHE],
    STARGATE_MAI[EvmChainId.ARBITRUM],
    STARGATE_MAI[EvmChainId.OPTIMISM],
  ],
}

const ARBITRUM_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[EvmChainId.ARBITRUM]]: [
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_BUSD[EvmChainId.BSC],
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_USDT_ADDRESS[EvmChainId.ARBITRUM]]: [
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_BUSD[EvmChainId.BSC],
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_USDC[EvmChainId.OPTIMISM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_FRAX_ADDRESS[EvmChainId.ARBITRUM]]: [
    STARGATE_FRAX[EvmChainId.ETHEREUM],
    STARGATE_FRAX[EvmChainId.AVALANCHE],
    STARGATE_FRAX[EvmChainId.OPTIMISM],
  ],
  [STARGATE_ETH_ADDRESS[EvmChainId.ARBITRUM]]: [
    STARGATE_ETH[EvmChainId.ETHEREUM],
    STARGATE_ETH[EvmChainId.OPTIMISM],
    STARGATE_ETH[EvmChainId.BASE],
    STARGATE_ETH[EvmChainId.LINEA],
  ],
  [STARGATE_MAI_ADDRESS[EvmChainId.ARBITRUM]]: [
    STARGATE_MAI[EvmChainId.ETHEREUM],
    STARGATE_MAI[EvmChainId.BSC],
    STARGATE_MAI[EvmChainId.AVALANCHE],
    STARGATE_MAI[EvmChainId.POLYGON],
    STARGATE_MAI[EvmChainId.OPTIMISM],
  ],
}

const OPTIMISM_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[EvmChainId.OPTIMISM]]: [
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_BUSD[EvmChainId.BSC],
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.FANTOM],
    STARGATE_USDC[EvmChainId.BASE],
  ],
  [STARGATE_DAI_ADDRESS[EvmChainId.OPTIMISM]]: [
    STARGATE_DAI[EvmChainId.ETHEREUM],
    STARGATE_DAI[EvmChainId.POLYGON],
  ],
  [STARGATE_FRAX_ADDRESS[EvmChainId.OPTIMISM]]: [
    STARGATE_FRAX[EvmChainId.ETHEREUM],
    STARGATE_FRAX[EvmChainId.AVALANCHE],
    STARGATE_FRAX[EvmChainId.ARBITRUM],
  ],
  [STARGATE_ETH_ADDRESS[EvmChainId.OPTIMISM]]: [
    STARGATE_ETH[EvmChainId.ETHEREUM],
    STARGATE_ETH[EvmChainId.ARBITRUM],
    STARGATE_ETH[EvmChainId.BASE],
    STARGATE_ETH[EvmChainId.LINEA],
  ],
  [STARGATE_MAI_ADDRESS[EvmChainId.OPTIMISM]]: [
    STARGATE_MAI[EvmChainId.ETHEREUM],
    STARGATE_MAI[EvmChainId.BSC],
    STARGATE_MAI[EvmChainId.AVALANCHE],
    STARGATE_MAI[EvmChainId.POLYGON],
    STARGATE_MAI[EvmChainId.ARBITRUM],
  ],
}

// const FANTOM_CHAIN_PATHS = {
//   [STARGATE_USDC_ADDRESS[EvmChainId.FANTOM]]: [
//     STARGATE_USDC[EvmChainId.ETHEREUM],
//     STARGATE_USDT[EvmChainId.ETHEREUM],
//     STARGATE_BUSD[EvmChainId.BSC],
//     STARGATE_USDT[EvmChainId.BSC],
//     STARGATE_USDC[EvmChainId.AVALANCHE],
//     STARGATE_USDT[EvmChainId.AVALANCHE],
//     STARGATE_USDC[EvmChainId.POLYGON],
//     STARGATE_USDT[EvmChainId.POLYGON],
//     STARGATE_USDC[EvmChainId.ARBITRUM],
//     STARGATE_USDT[EvmChainId.ARBITRUM],
//     STARGATE_USDC[EvmChainId.OPTIMISM],
//   ],
// }

const BASE_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[EvmChainId.BASE]]: [
    STARGATE_USDC[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.ETHEREUM],
    STARGATE_USDT[EvmChainId.BSC],
    STARGATE_USDC[EvmChainId.AVALANCHE],
    STARGATE_USDT[EvmChainId.AVALANCHE],
    STARGATE_USDC[EvmChainId.POLYGON],
    STARGATE_USDT[EvmChainId.POLYGON],
    STARGATE_USDC[EvmChainId.ARBITRUM],
    STARGATE_USDT[EvmChainId.ARBITRUM],
    STARGATE_USDC[EvmChainId.OPTIMISM],
  ],
  [STARGATE_ETH_ADDRESS[EvmChainId.BASE]]: [
    STARGATE_ETH[EvmChainId.ETHEREUM],
    STARGATE_ETH[EvmChainId.ARBITRUM],
    STARGATE_ETH[EvmChainId.OPTIMISM],
    STARGATE_ETH[EvmChainId.LINEA],
  ],
}

const LINEA_CHAIN_PATHS = {
  [STARGATE_ETH_ADDRESS[EvmChainId.LINEA]]: [
    STARGATE_ETH[EvmChainId.ETHEREUM],
    STARGATE_ETH[EvmChainId.ARBITRUM],
    STARGATE_ETH[EvmChainId.OPTIMISM],
    STARGATE_ETH[EvmChainId.BASE],
  ],
}

export const STARGATE_CHAIN_PATHS: Record<
  StargateChainId,
  Record<`0x${string}`, Token[]>
> = {
  [EvmChainId.ETHEREUM]: ETHEREUM_CHAIN_PATHS,
  [EvmChainId.BSC]: BSC_CHAIN_PATHS,
  [EvmChainId.AVALANCHE]: AVALANCE_CHAIN_PATHS,
  [EvmChainId.POLYGON]: POLYGON_CHAIN_PATHS,
  [EvmChainId.ARBITRUM]: ARBITRUM_CHAIN_PATHS,
  [EvmChainId.OPTIMISM]: OPTIMISM_CHAIN_PATHS,
  // [EvmChainId.FANTOM]: FANTOM_CHAIN_PATHS,
  [EvmChainId.BASE]: BASE_CHAIN_PATHS,
  [EvmChainId.LINEA]: LINEA_CHAIN_PATHS,
}
