import { EvmChainId } from '../chain/evm/index.js'

export const nativeCurrencyIds = {
  [EvmChainId.ETHEREUM]: 'ETH',
  [EvmChainId.SEPOLIA]: 'ETH',
  // [EvmChainId.ROPSTEN]: 'ETH',
  // [EvmChainId.RINKEBY]: 'ETH',
  // [EvmChainId.GÖRLI]: 'ETH',
  // [EvmChainId.KOVAN]: 'ETH',
  [EvmChainId.POLYGON]: 'MATIC',
  // [EvmChainId.POLYGON_TESTNET]: 'MATIC',
  [EvmChainId.FANTOM]: 'FTM',
  // [EvmChainId.FANTOM_TESTNET]: 'FTM',
  [EvmChainId.GNOSIS]: 'XDAI',
  [EvmChainId.BSC]: 'BNB',
  // [EvmChainId.BSC_TESTNET]: 'BNB',
  [EvmChainId.ARBITRUM]: 'ETH',
  [EvmChainId.ARBITRUM_NOVA]: 'ETH',
  // [EvmChainId.ARBITRUM_TESTNET]: 'ETH',
  [EvmChainId.AVALANCHE]: 'AVAX',
  // [EvmChainId.AVALANCHE_TESTNET]: 'AVAX',
  // [EvmChainId.HECO_TESTNET]: 'HT',
  [EvmChainId.HARMONY]: 'ONE',
  // [EvmChainId.HARMONY_TESTNET]: 'ONE',
  // [EvmChainId.OKEX_TESTNET]: 'OKT',
  [EvmChainId.CELO]: 'CELO',
  [EvmChainId.MOONRIVER]: 'MOVR',
  [EvmChainId.FUSE]: 'FUSE',
  [EvmChainId.TELOS]: 'TLOS',
  [EvmChainId.MOONBEAM]: 'GLMR',
  [EvmChainId.OPTIMISM]: 'ETH',
  [EvmChainId.KAVA]: 'KAVA',
  [EvmChainId.METIS]: 'METIS',
  [EvmChainId.BOBA]: 'ETH',
  [EvmChainId.BOBA_BNB]: 'BOBA',
  [EvmChainId.BTTC]: 'BTT',
  [EvmChainId.THUNDERCORE]: 'TT',
  // [EvmChainId.CONSENSUS_ZKEVM_TESTNET]: 'ETH',
  // [EvmChainId.SCROLL_ALPHA_TESTNET]: 'ETH',
  // [EvmChainId.BASE_TESTNET]: 'ETH',
  [EvmChainId.POLYGON_ZKEVM]: 'ETH',
  [EvmChainId.CORE]: 'CORE',
  [EvmChainId.HAQQ]: 'ISLM',
  [EvmChainId.ZKSYNC_ERA]: 'ETH',
  [EvmChainId.LINEA]: 'ETH',
  [EvmChainId.BASE]: 'ETH',
  [EvmChainId.SCROLL]: 'ETH',
  // [EvmChainId.SEPOLIA]: 'ETH',
  [EvmChainId.FILECOIN]: 'FIL',
  [EvmChainId.ZETACHAIN]: 'ZETA',
  [EvmChainId.CRONOS]: 'CRO',
  [EvmChainId.BLAST]: 'ETH',
  [EvmChainId.SKALE_EUROPA]: 'sFUEL',
  [EvmChainId.ROOTSTOCK]: 'RBTC',
  [EvmChainId.MANTLE]: 'MNT',
  // [EvmChainId.CURTIS]: 'APE',
  [EvmChainId.MANTA]: 'ETH',
  [EvmChainId.MODE]: 'ETH',
  [EvmChainId.TAIKO]: 'ETH',
  [EvmChainId.ZKLINK]: 'ETH',
  [EvmChainId.APE]: 'APE',
  [EvmChainId.SONIC]: 'S',
  [EvmChainId.HEMI]: 'ETH',
  [EvmChainId.TATARA]: 'ETH',
  [EvmChainId.KATANA]: 'ETH',
  [EvmChainId.HYPEREVM]: 'HYPE',
} as const
