import { EvmChainId } from '../../../chain/index.js'
import { EvmToken } from '../../../currency/token.js'
import { AUSD } from '../tokens/AUSD.js'
import { RBTC } from '../tokens/RBTC.js'
import { SolvBTC } from '../tokens/SolvBTC.js'
import { USDT0 } from '../tokens/USDT0.js'
import {
  AAVE,
  AERO,
  APE_ETH,
  APE_USD,
  BUSD,
  DAI,
  DOC,
  ETHEREUM_CRV_USD,
  ETHEREUM_STETH,
  ETHEREUM_THREE_CRV,
  FRAX,
  GUSD,
  LINK,
  LUSD,
  MATIC,
  METH,
  MIM,
  OHM,
  OP,
  QUICK,
  SKL,
  STONE,
  SUSHI,
  USDB,
  USDC,
  USDP,
  USDT,
  USDe,
  WBTC,
  WETH9,
  WstETH,
  ZETA_USDC_BSC,
  ZETA_USDC_ETH,
  ZETA_USDT_BSC,
  ZETA_USDT_ETH,
  axlETH,
  axlUSDC,
  axlWBTC,
  rETH,
} from '../tokens/index.js'
import { WNATIVE } from '../wrapped-native.js'

export const BASES_TO_CHECK_TRADES_AGAINST: {
  readonly [chainId: number]: EvmToken[]
} = {
  [EvmChainId.ETHEREUM]: [
    WNATIVE[EvmChainId.ETHEREUM],
    WBTC[EvmChainId.ETHEREUM],
    USDC[EvmChainId.ETHEREUM],
    USDT[EvmChainId.ETHEREUM],
    DAI[EvmChainId.ETHEREUM],
    MIM[EvmChainId.ETHEREUM],
    FRAX[EvmChainId.ETHEREUM],
    OHM[EvmChainId.ETHEREUM],
    LINK[EvmChainId.ETHEREUM],
    SUSHI[EvmChainId.ETHEREUM],
    WstETH[EvmChainId.ETHEREUM],
    ETHEREUM_STETH[EvmChainId.ETHEREUM],
    ETHEREUM_THREE_CRV[EvmChainId.ETHEREUM],
    GUSD[EvmChainId.ETHEREUM],
    LUSD[EvmChainId.ETHEREUM],
    ETHEREUM_CRV_USD[EvmChainId.ETHEREUM],
    new EvmToken({
      chainId: EvmChainId.ETHEREUM,
      address: '0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b',
      symbol: 'CRO',
      name: 'CRO',
      decimals: 8,
    }),
  ],
  [EvmChainId.POLYGON]: [
    WNATIVE[EvmChainId.POLYGON],
    WETH9[EvmChainId.POLYGON],
    WBTC[EvmChainId.POLYGON],
    USDC[EvmChainId.POLYGON],
    USDT[EvmChainId.POLYGON],
    DAI[EvmChainId.POLYGON],
    FRAX[EvmChainId.POLYGON],
    QUICK[EvmChainId.POLYGON],
    LINK[EvmChainId.POLYGON],
    AAVE[EvmChainId.POLYGON],
    new EvmToken({
      address: '0x2791bca1f2de4661ed88a30c99a7a9449aa84174',
      chainId: EvmChainId.POLYGON,
      decimals: 6,
      symbol: 'USD Coin',
      name: 'USDC.e',
    }),
  ],
  [EvmChainId.FANTOM]: [
    WNATIVE[EvmChainId.FANTOM],
    new EvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0x28a92dde19d9989f39a49905d7c9c2fac7799bdf',
      decimals: 6,
      symbol: 'USDC',
      name: 'USD Coin',
      // origin: 'stargate'
    }),
    new EvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0xcc1b99ddac1a33c201a742a1851662e87bc7f22c',
      decimals: 6,
      symbol: 'USDT',
      name: 'Tether USD',
      // origin: 'stargate'
    }),
    new EvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0x695921034f0387eac4e11620ee91b1b15a6a09fe',
      decimals: 18,
      symbol: 'WETH',
      name: 'Wrapped Ether',
      // origin: 'stargate'
    }),
    new EvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0xf1648c50d2863f780c57849d812b4b7686031a3d',
      decimals: 18,
      symbol: 'WBTC',
      name: 'Wrapped BTC',
      // origin: 'stargate'
    }),
    axlUSDC[EvmChainId.FANTOM],
    MIM[EvmChainId.FANTOM],
  ],
  [EvmChainId.GNOSIS]: [
    WNATIVE[EvmChainId.GNOSIS],
    WETH9[EvmChainId.GNOSIS],
    USDC[EvmChainId.GNOSIS],
    USDT[EvmChainId.GNOSIS],
    WstETH[EvmChainId.GNOSIS], // #3 token for other projects
    new EvmToken({
      chainId: EvmChainId.GNOSIS,
      address: '0x9c58bacc331c9aa871afd802db6379a98e80cedb',
      decimals: 18,
      symbol: 'GNO',
      name: 'Gnosis',
    }),
    new EvmToken({
      // #2 token for other projects
      chainId: EvmChainId.GNOSIS,
      address: '0xaf204776c7245bf4147c2612bf6e5972ee483701',
      decimals: 18,
      symbol: 'sDAI',
      name: 'Savings xDAI',
    }),
  ],
  [EvmChainId.BSC]: [
    WNATIVE[EvmChainId.BSC],
    WETH9[EvmChainId.BSC],
    USDC[EvmChainId.BSC],
    USDT[EvmChainId.BSC],
    DAI[EvmChainId.BSC],
    BUSD[EvmChainId.BSC],
    new EvmToken({
      chainId: EvmChainId.BSC,
      address: '0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c',
      decimals: 18,
      symbol: 'BTCB',
      name: 'Binance-Peg BTCB Token',
    }),
    new EvmToken({
      chainId: EvmChainId.BSC,
      address: '0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82',
      decimals: 18,
      symbol: 'Cake',
      name: 'PancakeSwap Token',
    }),
  ],
  [EvmChainId.ARBITRUM]: [
    WNATIVE[EvmChainId.ARBITRUM],
    WBTC[EvmChainId.ARBITRUM],
    USDC[EvmChainId.ARBITRUM],
    USDT[EvmChainId.ARBITRUM],
    DAI[EvmChainId.ARBITRUM],
    FRAX[EvmChainId.ARBITRUM],
    LINK[EvmChainId.ARBITRUM],
    WstETH[EvmChainId.ARBITRUM], // #5 for us, #6 for other projects
    new EvmToken({
      chainId: EvmChainId.ARBITRUM,
      address: '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8',
      decimals: 6,
      symbol: 'USDC.e',
      name: 'Bridged USDC (Arb1)',
    }),
    new EvmToken({
      chainId: EvmChainId.ARBITRUM,
      address: '0x912ce59144191c1204e64559fe8253a0e49e6548',
      decimals: 18,
      symbol: 'ARB',
      name: 'Arbitrum',
    }),
    new EvmToken({
      chainId: EvmChainId.ARBITRUM,
      address: '0x539bde0d7dbd336b79148aa742883198bbf60342',
      decimals: 18,
      symbol: 'MAGIC',
      name: 'MAGIC',
    }),
    new EvmToken({
      chainId: EvmChainId.ARBITRUM,
      address: '0x8d9ba570d6cb60c7e3e0f31343efe75ab8e65fb1',
      decimals: 18,
      symbol: 'gOHM',
      name: 'Governance OHM',
    }),
  ],
  [EvmChainId.ARBITRUM_NOVA]: [
    WNATIVE[EvmChainId.ARBITRUM_NOVA],
    WBTC[EvmChainId.ARBITRUM_NOVA],
    USDC[EvmChainId.ARBITRUM_NOVA],
    USDT[EvmChainId.ARBITRUM_NOVA],
    DAI[EvmChainId.ARBITRUM_NOVA],
    new EvmToken({
      chainId: EvmChainId.ARBITRUM_NOVA,
      address: '0xf823c3cd3cebe0a1fa952ba88dc9eef8e0bf46ad',
      decimals: 18,
      symbol: 'ARB',
      name: 'Arbitrum',
    }),
    SUSHI[EvmChainId.ARBITRUM_NOVA],
  ],
  [EvmChainId.AVALANCHE]: [
    WNATIVE[EvmChainId.AVALANCHE],
    WETH9[EvmChainId.AVALANCHE],
    WBTC[EvmChainId.AVALANCHE],
    USDC[EvmChainId.AVALANCHE],
    new EvmToken({
      chainId: EvmChainId.AVALANCHE,
      address: '0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664',
      decimals: 6,
      symbol: 'USDC.e',
      name: 'USD Coin',
    }),
    new EvmToken({
      // #4 token for other projects
      chainId: EvmChainId.AVALANCHE,
      address: '0x152b9d0fdc40c096757f570a51e494bd4b943e50',
      decimals: 8,
      symbol: 'BTC.b',
      name: 'USD Coin',
    }),
    new EvmToken({
      // #7 token for other projects
      chainId: EvmChainId.AVALANCHE,
      address: '0x2b2c81e08f1af8835a78bb2a90ae924ace0ea4be',
      decimals: 18,
      symbol: 'sAVAX',
      name: 'Staked AVAX',
    }),
    USDT[EvmChainId.AVALANCHE],
    new EvmToken({
      chainId: EvmChainId.AVALANCHE,
      address: '0xc7198437980c041c805a1edcba50c1ce5db95118',
      decimals: 6,
      symbol: 'USDT.e',
      name: 'Tether USD',
    }),
    new EvmToken({
      chainId: EvmChainId.AVALANCHE,
      address: '0xd586e7f844cea2f87f50152665bcbc2c279d8d70',
      decimals: 18,
      symbol: 'DAI.e',
      name: 'Dai Stablecoin',
    }),
    MIM[EvmChainId.AVALANCHE],
    new EvmToken({
      chainId: EvmChainId.AVALANCHE,
      address: '0x0da67235dd5787d67955420c84ca1cecd4e5bb3b',
      decimals: 18,
      name: 'Wrapped MEMO',
      symbol: 'WMEMO',
    }),
  ],
  [EvmChainId.HARMONY]: [
    WNATIVE[EvmChainId.HARMONY],
    USDC[EvmChainId.HARMONY],
    USDT[EvmChainId.HARMONY],
    DAI[EvmChainId.HARMONY],
    FRAX[EvmChainId.HARMONY],
  ],
  [EvmChainId.CELO]: [
    WNATIVE[EvmChainId.CELO],
    WETH9[EvmChainId.CELO],
    WBTC[EvmChainId.CELO],
    USDC[EvmChainId.CELO],
    USDT[EvmChainId.CELO],
    DAI[EvmChainId.CELO],
    new EvmToken({
      chainId: EvmChainId.CELO,
      address: '0xd8763cba276a3738e6de85b4b3bf5fded6d6ca73',
      decimals: 18,
      symbol: 'cEUR',
      name: 'Celo Euro',
    }),
    new EvmToken({
      chainId: EvmChainId.CELO,
      address: '0x765de816845861e75a25fca122bb6898b8b1282a',
      decimals: 18,
      symbol: 'cUSD',
      name: 'Celo Dollar',
    }),
    new EvmToken({
      chainId: EvmChainId.CELO,
      address: '0x2def4285787d58a2f811af24755a8150622f4361',
      decimals: 18,
      symbol: 'cETH',
      name: 'Celo Ether',
    }),
    new EvmToken({
      chainId: EvmChainId.CELO,
      address: '0x66803fb87abd4aac3cbb3fad7c3aa01f6f3fb207',
      decimals: 18,
      symbol: 'WETH',
      name: 'Wrapped Ether (Wormhole)',
    }),
  ],
  [EvmChainId.OPTIMISM]: [
    WNATIVE[EvmChainId.OPTIMISM],
    WBTC[EvmChainId.OPTIMISM],
    USDC[EvmChainId.OPTIMISM],
    new EvmToken({
      chainId: EvmChainId.OPTIMISM,
      address: '0x7f5c764cbc14f9669b88837ca1490cca17c31607',
      decimals: 6,
      symbol: 'USDC',
      name: 'USD Coin (Bridged from Ethereum)',
    }),
    WstETH[EvmChainId.OPTIMISM], // #5 for other projects
    USDT[EvmChainId.OPTIMISM],
    DAI[EvmChainId.OPTIMISM],
    LUSD[EvmChainId.OPTIMISM],
    FRAX[EvmChainId.OPTIMISM],
    new EvmToken({
      chainId: EvmChainId.OPTIMISM,
      address: '0xc84da6c8ec7a57cd10b939e79eaf9d2d17834e04',
      decimals: 18,
      symbol: 'vUSD',
      name: 'vUSD',
    }),
    OP[EvmChainId.OPTIMISM],
  ],
  [EvmChainId.KAVA]: [
    WNATIVE[EvmChainId.KAVA],
    new EvmToken({
      chainId: EvmChainId.KAVA,
      address: '0x2dfd4de5ae386cd3f4fc8e2cb39240852e47f5e8',
      decimals: 18,
      symbol: 'WETH',
      name: 'Wrapped Ether',
      // origin: 'stargate'
    }),
    new EvmToken({
      chainId: EvmChainId.KAVA,
      address: '0xaad094f6a75a14417d39f04e690fc216f080a41a',
      decimals: 6,
      symbol: 'USDT',
      name: 'Tether USD',
      // origin: 'stargate'
    }),
    axlUSDC[EvmChainId.KAVA],
    axlETH[EvmChainId.KAVA],
    axlWBTC[EvmChainId.KAVA],
  ],
  [EvmChainId.METIS]: [
    WNATIVE[EvmChainId.METIS],
    WETH9[EvmChainId.METIS],
    WBTC[EvmChainId.METIS],
    USDC[EvmChainId.METIS],
    USDT[EvmChainId.METIS],
    DAI[EvmChainId.METIS],
  ],
  [EvmChainId.BOBA]: [
    WNATIVE[EvmChainId.BOBA],
    WBTC[EvmChainId.BOBA],
    USDC[EvmChainId.BOBA],
    USDT[EvmChainId.BOBA],
    DAI[EvmChainId.BOBA],
    FRAX[EvmChainId.BOBA],
  ],
  [EvmChainId.BOBA_BNB]: [
    WNATIVE[EvmChainId.BOBA_BNB],
    new EvmToken({
      chainId: EvmChainId.BOBA_BNB,
      address: '0x4200000000000000000000000000000000000023',
      decimals: 18,
      symbol: 'BNB',
      name: 'Binance Coin',
    }),
    USDT[EvmChainId.BOBA_BNB],
    USDC[EvmChainId.BOBA_BNB],
  ],
  [EvmChainId.BTTC]: [
    WNATIVE[EvmChainId.BTTC],
    WETH9[EvmChainId.BTTC],
    USDC[EvmChainId.BTTC],
    USDT[EvmChainId.BTTC],
  ],
  [EvmChainId.POLYGON_ZKEVM]: [
    WNATIVE[EvmChainId.POLYGON_ZKEVM],
    MATIC[EvmChainId.POLYGON_ZKEVM],
    USDC[EvmChainId.POLYGON_ZKEVM],
    USDT[EvmChainId.POLYGON_ZKEVM],
    DAI[EvmChainId.POLYGON_ZKEVM],
    WBTC[EvmChainId.POLYGON_ZKEVM],
    FRAX[EvmChainId.POLYGON_ZKEVM],
  ],
  [EvmChainId.THUNDERCORE]: [
    WNATIVE[EvmChainId.THUNDERCORE],
    WETH9[EvmChainId.THUNDERCORE],
    WBTC[EvmChainId.THUNDERCORE],
    USDC[EvmChainId.THUNDERCORE],
    USDT[EvmChainId.THUNDERCORE],
  ],
  [EvmChainId.HAQQ]: [
    WNATIVE[EvmChainId.HAQQ],
    WETH9[EvmChainId.HAQQ],
    WBTC[EvmChainId.HAQQ],
    USDC[EvmChainId.HAQQ],
    USDT[EvmChainId.HAQQ],
    DAI[EvmChainId.HAQQ],
  ],
  [EvmChainId.CORE]: [
    WNATIVE[EvmChainId.CORE],
    WETH9[EvmChainId.CORE],
    USDC[EvmChainId.CORE],
    USDT[EvmChainId.CORE],
  ],
  [EvmChainId.ZKSYNC_ERA]: [
    WNATIVE[EvmChainId.ZKSYNC_ERA],
    WBTC[EvmChainId.ZKSYNC_ERA],
    USDC[EvmChainId.ZKSYNC_ERA],
    USDT[EvmChainId.ZKSYNC_ERA],
    new EvmToken({
      chainId: EvmChainId.ZKSYNC_ERA,
      address: '0x5a7d6b2f92c77fad6ccabd7ee0624e64907eaf3e',
      decimals: 18,
      symbol: 'ZK',
      name: 'ZKsync',
    }),
    new EvmToken({
      // real USDC (not bridged)
      chainId: EvmChainId.ZKSYNC_ERA,
      address: '0x1d17cbcf0d6d143135ae902365d2e5e2a16538d4',
      decimals: 6,
      symbol: 'USDC',
      name: 'USDC',
    }),
  ],
  [EvmChainId.LINEA]: [
    WNATIVE[EvmChainId.LINEA],
    USDC[EvmChainId.LINEA],
    USDT[EvmChainId.LINEA],
    DAI[EvmChainId.LINEA],
    WBTC[EvmChainId.LINEA],
  ],
  [EvmChainId.BASE]: [
    WNATIVE[EvmChainId.BASE],
    new EvmToken({
      chainId: EvmChainId.BASE,
      address: '0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22',
      decimals: 18,
      symbol: 'cbETH',
      name: 'Coinbase Wrapped Staked ETH',
    }),
    USDC[EvmChainId.BASE],
    WstETH[EvmChainId.BASE], // #7  for other projects
    USDT[EvmChainId.BASE], // #8  for other projects
    AERO[EvmChainId.BASE], // #9  for other projects
    new EvmToken({
      chainId: EvmChainId.BASE,
      address: '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca',
      decimals: 6,
      symbol: 'USDbC',
      name: 'USD Base Coin',
    }),
    axlUSDC[EvmChainId.BASE],
    DAI[EvmChainId.BASE],
    new EvmToken({
      chainId: EvmChainId.BASE,
      address: '0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf',
      decimals: 8,
      symbol: 'cbBTC',
      name: 'Coinbase Wrapped BTC',
    }),
    new EvmToken({
      chainId: EvmChainId.BASE,
      address: '0x0b3e328455c4059eeb9e3f84b5543f74e24e7e1b',
      decimals: 18,
      symbol: 'VIRTUAL',
      name: 'Virtual Protocol',
    }),
  ],
  [EvmChainId.SCROLL]: [
    WNATIVE[EvmChainId.SCROLL],
    WBTC[EvmChainId.SCROLL],
    USDC[EvmChainId.SCROLL],
    USDT[EvmChainId.SCROLL],
    WstETH[EvmChainId.SCROLL],
  ],
  [EvmChainId.FILECOIN]: [
    WNATIVE[EvmChainId.FILECOIN],
    USDC[EvmChainId.FILECOIN],
    DAI[EvmChainId.FILECOIN],
  ],
  [EvmChainId.ZETACHAIN]: [
    WNATIVE[EvmChainId.ZETACHAIN],
    WETH9[EvmChainId.ZETACHAIN],
    WBTC[EvmChainId.ZETACHAIN],
    ZETA_USDC_ETH[EvmChainId.ZETACHAIN],
    ZETA_USDT_ETH[EvmChainId.ZETACHAIN],
    ZETA_USDC_BSC[EvmChainId.ZETACHAIN],
    ZETA_USDT_BSC[EvmChainId.ZETACHAIN],
  ],
  [EvmChainId.CRONOS]: [
    WNATIVE[EvmChainId.CRONOS],
    WETH9[EvmChainId.CRONOS],
    WBTC[EvmChainId.CRONOS],
    USDC[EvmChainId.CRONOS],
  ],
  [EvmChainId.BLAST]: [WNATIVE[EvmChainId.BLAST], USDB[EvmChainId.BLAST]],
  [EvmChainId.SKALE_EUROPA]: [
    SKL[EvmChainId.SKALE_EUROPA],
    USDT[EvmChainId.SKALE_EUROPA],
    USDC[EvmChainId.SKALE_EUROPA],
    DAI[EvmChainId.SKALE_EUROPA],
    USDP[EvmChainId.SKALE_EUROPA],
    WETH9[EvmChainId.SKALE_EUROPA],
    rETH[EvmChainId.SKALE_EUROPA],
  ],
  [EvmChainId.ROOTSTOCK]: [
    WNATIVE[EvmChainId.ROOTSTOCK],
    WETH9[EvmChainId.ROOTSTOCK],
    USDT[EvmChainId.ROOTSTOCK],
    DOC[EvmChainId.ROOTSTOCK],
    SolvBTC[EvmChainId.ROOTSTOCK],
    USDT0[EvmChainId.ROOTSTOCK],
    RBTC[EvmChainId.ROOTSTOCK],
  ],
  [EvmChainId.MANTLE]: [
    WNATIVE[EvmChainId.MANTLE],
    WETH9[EvmChainId.MANTLE],
    USDC[EvmChainId.MANTLE],
    USDT[EvmChainId.MANTLE],
    METH[EvmChainId.MANTLE],
    USDe[EvmChainId.MANTLE],
  ],
  [EvmChainId.MANTA]: [
    WNATIVE[EvmChainId.MANTA],
    USDC[EvmChainId.MANTA],
    USDT[EvmChainId.MANTA],
    STONE[EvmChainId.MANTA],
  ],
  [EvmChainId.MODE]: [
    WNATIVE[EvmChainId.MODE],
    USDC[EvmChainId.MODE],
    USDT[EvmChainId.MODE],
  ],
  [EvmChainId.TAIKO]: [
    WNATIVE[EvmChainId.TAIKO],
    USDC[EvmChainId.TAIKO],
    USDT[EvmChainId.TAIKO],
    DAI[EvmChainId.TAIKO],
  ],
  [EvmChainId.ZKLINK]: [
    WNATIVE[EvmChainId.ZKLINK],
    USDC[EvmChainId.ZKLINK],
    USDT[EvmChainId.ZKLINK],
    DAI[EvmChainId.ZKLINK],
  ],
  [EvmChainId.APE]: [
    WNATIVE[EvmChainId.APE],
    APE_USD[EvmChainId.APE],
    APE_ETH[EvmChainId.APE],
  ],
  [EvmChainId.SONIC]: [
    WNATIVE[EvmChainId.SONIC],
    USDC[EvmChainId.SONIC],
    WETH9[EvmChainId.SONIC],
  ],
  [EvmChainId.HEMI]: [
    WNATIVE[EvmChainId.HEMI],
    USDC[EvmChainId.HEMI],
    USDT[EvmChainId.HEMI],
  ],
  [EvmChainId.TATARA]: [WNATIVE[EvmChainId.TATARA], AUSD[EvmChainId.TATARA]],
  [EvmChainId.KATANA]: [
    WNATIVE[EvmChainId.KATANA],
    USDC[EvmChainId.KATANA],
    USDT[EvmChainId.KATANA],
    AUSD[EvmChainId.KATANA],
    WBTC[EvmChainId.KATANA],
    new EvmToken({
      chainId: EvmChainId.KATANA,
      address: '0x9b8df6e244526ab5f6e6400d331db28c8fdddb55',
      name: 'Solana (Universal)',
      symbol: 'uSOL',
      decimals: 18,
    }),
  ],
  [EvmChainId.HYPEREVM]: [
    WNATIVE[EvmChainId.HYPEREVM],
    USDT[EvmChainId.HYPEREVM],
  ],
}
