import { getAddress as _getAddress } from 'viem/utils'
import { EvmChainId } from '~evm/chain/index.js'
import {
  APE_USD,
  ARB,
  DAI,
  FRAX,
  GNO,
  MATIC,
  MIM,
  SKL,
  SUSHI,
  USDB,
  USDC,
  USDT,
  WBTC,
  WETH9,
  ZETA_USDC_ETH,
  ZETA_USDT_ETH,
  axlDAI,
  axlETH,
  axlUSDC,
  axlUSDT,
  axlWBTC,
} from '~evm/config/tokens/tokens/index.js'
import { WNATIVE } from '../wrapped-native.js'
import { getEvmNativeByChainId } from '~evm/currency/native.js'
import type { EvmCurrency } from '~evm/currency/currency.js'
import { createEvmToken } from '~evm/currency/token.js'

/*
  Currencies that are shown at the top of the token selector by default
*/
export const EVM_DEFAULT_BASES = {
  [EvmChainId.ETHEREUM]: [
    getEvmNativeByChainId(EvmChainId.ETHEREUM),
    WNATIVE[EvmChainId.ETHEREUM],
    SUSHI[EvmChainId.ETHEREUM],
    WBTC[EvmChainId.ETHEREUM],
    USDC[EvmChainId.ETHEREUM],
    USDT[EvmChainId.ETHEREUM],
    DAI[EvmChainId.ETHEREUM],
  ],
  [EvmChainId.SEPOLIA]: [
    getEvmNativeByChainId(EvmChainId.SEPOLIA),
    WNATIVE[EvmChainId.SEPOLIA],
    USDC[EvmChainId.SEPOLIA],
  ],
  [EvmChainId.GNOSIS]: [
    getEvmNativeByChainId(EvmChainId.GNOSIS),
    WNATIVE[EvmChainId.GNOSIS],
    GNO[EvmChainId.GNOSIS],
    WETH9[EvmChainId.GNOSIS],
    USDC[EvmChainId.GNOSIS],
    USDT[EvmChainId.GNOSIS],
    DAI[EvmChainId.GNOSIS],
  ],
  [EvmChainId.BSC]: [
    getEvmNativeByChainId(EvmChainId.BSC),
    WNATIVE[EvmChainId.BSC],
    WETH9[EvmChainId.BSC],
    USDC[EvmChainId.BSC],
    USDT[EvmChainId.BSC],
    DAI[EvmChainId.BSC],
  ],
  [EvmChainId.BSC_TESTNET]: [],
  [EvmChainId.POLYGON]: [
    getEvmNativeByChainId(EvmChainId.POLYGON),
    WNATIVE[EvmChainId.POLYGON],
    WBTC[EvmChainId.POLYGON],
    WETH9[EvmChainId.POLYGON],
    USDC[EvmChainId.POLYGON],
    USDT[EvmChainId.POLYGON],
    DAI[EvmChainId.POLYGON],
  ],
  [EvmChainId.AVALANCHE]: [
    getEvmNativeByChainId(EvmChainId.AVALANCHE),
    WNATIVE[EvmChainId.AVALANCHE],
    WETH9[EvmChainId.AVALANCHE],
    WBTC[EvmChainId.AVALANCHE],
    USDC[EvmChainId.AVALANCHE],
    USDT[EvmChainId.AVALANCHE],
    DAI[EvmChainId.AVALANCHE],
    MIM[EvmChainId.AVALANCHE],
    FRAX[EvmChainId.AVALANCHE],
  ],
  [EvmChainId.ARBITRUM_NOVA]: [
    getEvmNativeByChainId(EvmChainId.ARBITRUM_NOVA),
    WNATIVE[EvmChainId.ARBITRUM_NOVA],
    ARB[EvmChainId.ARBITRUM_NOVA],
    WBTC[EvmChainId.ARBITRUM_NOVA],
    USDC[EvmChainId.ARBITRUM_NOVA],
    USDT[EvmChainId.ARBITRUM_NOVA],
    DAI[EvmChainId.ARBITRUM_NOVA],
  ],
  [EvmChainId.BOBA]: [
    getEvmNativeByChainId(EvmChainId.BOBA),
    WNATIVE[EvmChainId.BOBA],
    USDC[EvmChainId.BOBA],
    USDT[EvmChainId.BOBA],
    DAI[EvmChainId.BOBA],
    FRAX[EvmChainId.BOBA],
    WBTC[EvmChainId.BOBA],
  ],
  [EvmChainId.FANTOM]: [
    getEvmNativeByChainId(EvmChainId.FANTOM),
    WNATIVE[EvmChainId.FANTOM],
    axlUSDC[EvmChainId.FANTOM],
    createEvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0x28a92dde19D9989F39A49905d7C9C2FAc7799bDf',
      decimals: 6,
      symbol: 'USDC',
      name: 'USD Coin',
      // origin: 'stargate'
    }),
    createEvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0xcc1b99dDAc1a33c201a742A1851662E87BC7f22C',
      decimals: 6,
      symbol: 'USDT',
      name: 'Tether USD',
      // origin: 'stargate'
    }),
    createEvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0x695921034f0387eAc4e11620EE91b1b15A6A09fE',
      decimals: 18,
      symbol: 'WETH',
      name: 'Wrapped Ether',
      // origin: 'stargate'
    }),
    createEvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0xf1648C50d2863f780c57849D812b4B7686031A3D',
      decimals: 18,
      symbol: 'WBTC',
      name: 'Wrapped BTC',
      // origin: 'stargate'
    }),
    axlUSDC[EvmChainId.FANTOM],
    MIM[EvmChainId.FANTOM],
  ],
  [EvmChainId.FANTOM_TESTNET]: [],
  [EvmChainId.ARBITRUM]: [
    getEvmNativeByChainId(EvmChainId.ARBITRUM),
    WNATIVE[EvmChainId.ARBITRUM],
    ARB[EvmChainId.ARBITRUM],
    WBTC[EvmChainId.ARBITRUM],
    USDC[EvmChainId.ARBITRUM],
    USDT[EvmChainId.ARBITRUM],
    DAI[EvmChainId.ARBITRUM],
    MIM[EvmChainId.ARBITRUM],
  ],
  [EvmChainId.ARBITRUM_SEPOLIA]: [],
  [EvmChainId.HARMONY]: [
    getEvmNativeByChainId(EvmChainId.HARMONY),
    WNATIVE[EvmChainId.HARMONY],
    WETH9[EvmChainId.HARMONY],
    USDC[EvmChainId.HARMONY],
    USDT[EvmChainId.HARMONY],
    DAI[EvmChainId.HARMONY],
  ],
  [EvmChainId.CELO]: [
    getEvmNativeByChainId(EvmChainId.CELO),
    // WNATIVE[EvmChainId.CELO],
    WETH9[EvmChainId.CELO],
    USDC[EvmChainId.CELO],
    USDT[EvmChainId.CELO],
    DAI[EvmChainId.CELO],
  ],
  [EvmChainId.OPTIMISM]: [
    getEvmNativeByChainId(EvmChainId.OPTIMISM),
    WNATIVE[EvmChainId.OPTIMISM],
    WBTC[EvmChainId.OPTIMISM],
    USDC[EvmChainId.OPTIMISM],
    USDT[EvmChainId.OPTIMISM],
    DAI[EvmChainId.OPTIMISM],
  ],
  [EvmChainId.KAVA]: [
    getEvmNativeByChainId(EvmChainId.KAVA),
    WNATIVE[EvmChainId.KAVA],
    axlWBTC[EvmChainId.KAVA],
    createEvmToken({
      chainId: EvmChainId.KAVA,
      address: '0x2DfD4dE5AE386Cd3f4fC8e2cb39240852E47F5E8',
      decimals: 18,
      symbol: 'WETH',
      name: 'Wrapped Ether',
      // origin: 'stargate'
    }),
    axlUSDC[EvmChainId.KAVA],
    USDT[EvmChainId.KAVA],
  ],
  [EvmChainId.METIS]: [
    getEvmNativeByChainId(EvmChainId.METIS),
    WNATIVE[EvmChainId.METIS],
    WBTC[EvmChainId.METIS],
    WETH9[EvmChainId.METIS],
    USDC[EvmChainId.METIS],
    USDT[EvmChainId.METIS],
    DAI[EvmChainId.METIS],
  ],
  [EvmChainId.BOBA_BNB]: [
    getEvmNativeByChainId(EvmChainId.BOBA_BNB),
    WNATIVE[EvmChainId.BOBA_BNB],
    createEvmToken({
      chainId: EvmChainId.BOBA_BNB,
      symbol: 'BNB',
      name: 'Binance Coin',
      decimals: 18,
      address: '0x4200000000000000000000000000000000000023',
    }),
    USDC[EvmChainId.BOBA_BNB],
    USDT[EvmChainId.BOBA_BNB],
  ],
  [EvmChainId.BTTC]: [
    getEvmNativeByChainId(EvmChainId.BTTC),
    WNATIVE[EvmChainId.BTTC],
    WETH9[EvmChainId.BTTC],
    USDC[EvmChainId.BTTC],
    USDT[EvmChainId.BTTC],
  ],
  [EvmChainId.POLYGON_ZKEVM]: [
    getEvmNativeByChainId(EvmChainId.POLYGON_ZKEVM),
    WNATIVE[EvmChainId.POLYGON_ZKEVM],
    MATIC[EvmChainId.POLYGON_ZKEVM],
    USDC[EvmChainId.POLYGON_ZKEVM],
    USDT[EvmChainId.POLYGON_ZKEVM],
    DAI[EvmChainId.POLYGON_ZKEVM],
    WBTC[EvmChainId.POLYGON_ZKEVM],
  ],
  [EvmChainId.THUNDERCORE]: [
    getEvmNativeByChainId(EvmChainId.THUNDERCORE),
    WNATIVE[EvmChainId.THUNDERCORE],
    WETH9[EvmChainId.THUNDERCORE],
    USDC[EvmChainId.THUNDERCORE],
    USDT[EvmChainId.THUNDERCORE],
    WBTC[EvmChainId.THUNDERCORE],
  ],
  [EvmChainId.HAQQ]: [
    getEvmNativeByChainId(EvmChainId.HAQQ),
    WNATIVE[EvmChainId.HAQQ],
    axlETH[EvmChainId.HAQQ],
    axlWBTC[EvmChainId.HAQQ],
    axlUSDC[EvmChainId.HAQQ],
    axlUSDT[EvmChainId.HAQQ],
    axlDAI[EvmChainId.HAQQ],
  ],
  [EvmChainId.CORE]: [
    getEvmNativeByChainId(EvmChainId.CORE),
    WNATIVE[EvmChainId.CORE],
    WETH9[EvmChainId.CORE],
    USDC[EvmChainId.CORE],
    USDT[EvmChainId.CORE],
  ],
  [EvmChainId.ZKSYNC_ERA]: [
    getEvmNativeByChainId(EvmChainId.ZKSYNC_ERA),
    WNATIVE[EvmChainId.ZKSYNC_ERA],
    WBTC[EvmChainId.ZKSYNC_ERA],
    USDC[EvmChainId.ZKSYNC_ERA],
  ],
  [EvmChainId.LINEA]: [
    getEvmNativeByChainId(EvmChainId.LINEA),
    WNATIVE[EvmChainId.LINEA],
    DAI[EvmChainId.LINEA],
    USDC[EvmChainId.LINEA],
  ],
  [EvmChainId.BASE]: [
    getEvmNativeByChainId(EvmChainId.BASE),
    WNATIVE[EvmChainId.BASE],
    DAI[EvmChainId.BASE],
    createEvmToken({
      chainId: EvmChainId.BASE,
      symbol: 'USDbC',
      name: 'USD Base Coin',
      decimals: 6,
      address: '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA',
    }),
    USDC[EvmChainId.BASE],
    createEvmToken({
      chainId: EvmChainId.BASE,
      symbol: 'OX',
      name: 'OX Coin',
      decimals: 18,
      address: '0xba0Dda8762C24dA9487f5FA026a9B64b695A07Ea',
    }),
  ],
  [EvmChainId.SCROLL]: [
    getEvmNativeByChainId(EvmChainId.SCROLL),
    WNATIVE[EvmChainId.SCROLL],
    USDC[EvmChainId.SCROLL],
    USDT[EvmChainId.SCROLL],
    WBTC[EvmChainId.SCROLL],
  ],
  [EvmChainId.FILECOIN]: [
    getEvmNativeByChainId(EvmChainId.FILECOIN),
    WNATIVE[EvmChainId.FILECOIN],
    USDC[EvmChainId.FILECOIN],
    DAI[EvmChainId.FILECOIN],
  ],
  [EvmChainId.ZETACHAIN]: [
    getEvmNativeByChainId(EvmChainId.ZETACHAIN),
    WNATIVE[EvmChainId.ZETACHAIN],
    ZETA_USDC_ETH[EvmChainId.ZETACHAIN],
    ZETA_USDT_ETH[EvmChainId.ZETACHAIN],
    WETH9[EvmChainId.ZETACHAIN],
  ],
  [EvmChainId.CRONOS]: [
    getEvmNativeByChainId(EvmChainId.CRONOS),
    WNATIVE[EvmChainId.CRONOS],
    WETH9[EvmChainId.CRONOS],
    WBTC[EvmChainId.CRONOS],
    USDC[EvmChainId.CRONOS],
  ],
  [EvmChainId.BLAST]: [
    getEvmNativeByChainId(EvmChainId.BLAST),
    USDB[EvmChainId.BLAST],
  ],
  [EvmChainId.SKALE_EUROPA]: [
    SKL[EvmChainId.SKALE_EUROPA],
    USDC[EvmChainId.SKALE_EUROPA],
    WETH9[EvmChainId.SKALE_EUROPA],
  ],
  [EvmChainId.ROOTSTOCK]: [
    getEvmNativeByChainId(EvmChainId.ROOTSTOCK),
    WNATIVE[EvmChainId.ROOTSTOCK],
    WETH9[EvmChainId.ROOTSTOCK],
    USDT[EvmChainId.ROOTSTOCK],
  ],
  [EvmChainId.MANTLE]: [
    getEvmNativeByChainId(EvmChainId.MANTLE),
    WNATIVE[EvmChainId.MANTLE],
    WETH9[EvmChainId.MANTLE],
    USDC[EvmChainId.MANTLE],
  ],
  [EvmChainId.CURTIS]: [
    getEvmNativeByChainId(EvmChainId.CURTIS),
    WNATIVE[EvmChainId.CURTIS],
  ],
  [EvmChainId.MANTA]: [
    getEvmNativeByChainId(EvmChainId.MANTA),
    WNATIVE[EvmChainId.MANTA],
    USDC[EvmChainId.MANTA],
    USDT[EvmChainId.MANTA],
    WBTC[EvmChainId.MANTA],
  ],
  [EvmChainId.MODE]: [
    getEvmNativeByChainId(EvmChainId.MODE),
    WNATIVE[EvmChainId.MODE],
    USDC[EvmChainId.MODE],
    USDT[EvmChainId.MODE],
    WBTC[EvmChainId.MODE],
  ],
  [EvmChainId.TAIKO]: [
    getEvmNativeByChainId(EvmChainId.TAIKO),
    WNATIVE[EvmChainId.TAIKO],
    USDC[EvmChainId.TAIKO],
    USDT[EvmChainId.TAIKO],
    DAI[EvmChainId.TAIKO],
    WBTC[EvmChainId.TAIKO],
  ],
  [EvmChainId.ZKLINK]: [
    getEvmNativeByChainId(EvmChainId.ZKLINK),
    WNATIVE[EvmChainId.ZKLINK],
    USDC[EvmChainId.ZKLINK],
    USDT[EvmChainId.ZKLINK],
    DAI[EvmChainId.ZKLINK],
    WBTC[EvmChainId.ZKLINK],
  ],
  [EvmChainId.APE]: [
    getEvmNativeByChainId(EvmChainId.APE),
    WNATIVE[EvmChainId.APE],
    APE_USD[EvmChainId.APE],
  ],
  [EvmChainId.SONIC]: [
    getEvmNativeByChainId(EvmChainId.SONIC),
    WNATIVE[EvmChainId.SONIC],
    USDC[EvmChainId.SONIC],
    WETH9[EvmChainId.SONIC],
  ],
  [EvmChainId.HEMI]: [
    getEvmNativeByChainId(EvmChainId.HEMI),
    WNATIVE[EvmChainId.HEMI],
    USDC[EvmChainId.HEMI],
    USDT[EvmChainId.HEMI],
  ],
} as const satisfies Record<EvmChainId, Readonly<EvmCurrency[]>>
