import { getAddress as _getAddress } from 'viem/utils'
import type { EvmCurrency } from '../../../../evm/currency/currency.js'
import { EvmChainId } from '../../../chain/index.js'
import {
  APE_USD,
  ARB,
  AUSD,
  DAI,
  FRAX,
  GNO,
  MATIC,
  MIM,
  RBTC,
  SKL,
  SUSHI,
  SolvBTC,
  USDB,
  USDC,
  USDT,
  USDT0,
  WBTC,
  WETH9,
  ZETA_USDC_ETH,
  ZETA_USDT_ETH,
  axlDAI,
  axlETH,
  axlUSDC,
  axlUSDT,
  axlWBTC,
} from '../../../config/tokens/tokens/index.js'
import { EvmNative } from '../../../currency/native.js'
import { EvmToken } from '../../../currency/token.js'
import { WNATIVE } from '../wrapped-native.js'

/*
  Currencies that are shown at the top of the token selector by default
*/
export const EVM_DEFAULT_BASES = {
  [EvmChainId.ETHEREUM]: [
    EvmNative.fromChainId(EvmChainId.ETHEREUM),
    WNATIVE[EvmChainId.ETHEREUM],
    SUSHI[EvmChainId.ETHEREUM],
    WBTC[EvmChainId.ETHEREUM],
    USDC[EvmChainId.ETHEREUM],
    USDT[EvmChainId.ETHEREUM],
    DAI[EvmChainId.ETHEREUM],
  ],
  [EvmChainId.SEPOLIA]: [
    EvmNative.fromChainId(EvmChainId.SEPOLIA),
    WNATIVE[EvmChainId.SEPOLIA],
    USDC[EvmChainId.SEPOLIA],
  ],
  [EvmChainId.GNOSIS]: [
    EvmNative.fromChainId(EvmChainId.GNOSIS),
    WNATIVE[EvmChainId.GNOSIS],
    GNO[EvmChainId.GNOSIS],
    WETH9[EvmChainId.GNOSIS],
    USDC[EvmChainId.GNOSIS],
    USDT[EvmChainId.GNOSIS],
    DAI[EvmChainId.GNOSIS],
  ],
  [EvmChainId.BSC]: [
    EvmNative.fromChainId(EvmChainId.BSC),
    WNATIVE[EvmChainId.BSC],
    WETH9[EvmChainId.BSC],
    USDC[EvmChainId.BSC],
    USDT[EvmChainId.BSC],
    DAI[EvmChainId.BSC],
  ],
  [EvmChainId.POLYGON]: [
    EvmNative.fromChainId(EvmChainId.POLYGON),
    WNATIVE[EvmChainId.POLYGON],
    WBTC[EvmChainId.POLYGON],
    WETH9[EvmChainId.POLYGON],
    USDC[EvmChainId.POLYGON],
    USDT[EvmChainId.POLYGON],
    DAI[EvmChainId.POLYGON],
  ],
  [EvmChainId.AVALANCHE]: [
    EvmNative.fromChainId(EvmChainId.AVALANCHE),
    WNATIVE[EvmChainId.AVALANCHE],
    WETH9[EvmChainId.AVALANCHE],
    WBTC[EvmChainId.AVALANCHE],
    USDC[EvmChainId.AVALANCHE],
    USDT[EvmChainId.AVALANCHE],
    DAI[EvmChainId.AVALANCHE],
    MIM[EvmChainId.AVALANCHE],
    FRAX[EvmChainId.AVALANCHE],
  ],
  [EvmChainId.ARBITRUM_NOVA]: [
    EvmNative.fromChainId(EvmChainId.ARBITRUM_NOVA),
    WNATIVE[EvmChainId.ARBITRUM_NOVA],
    ARB[EvmChainId.ARBITRUM_NOVA],
    WBTC[EvmChainId.ARBITRUM_NOVA],
    USDC[EvmChainId.ARBITRUM_NOVA],
    USDT[EvmChainId.ARBITRUM_NOVA],
    DAI[EvmChainId.ARBITRUM_NOVA],
  ],
  [EvmChainId.BOBA]: [
    EvmNative.fromChainId(EvmChainId.BOBA),
    WNATIVE[EvmChainId.BOBA],
    USDC[EvmChainId.BOBA],
    USDT[EvmChainId.BOBA],
    DAI[EvmChainId.BOBA],
    FRAX[EvmChainId.BOBA],
    WBTC[EvmChainId.BOBA],
  ],
  [EvmChainId.FANTOM]: [
    EvmNative.fromChainId(EvmChainId.FANTOM),
    WNATIVE[EvmChainId.FANTOM],
    axlUSDC[EvmChainId.FANTOM],
    new EvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0x28a92dde19d9989f39a49905d7c9c2fac7799bdf',
      decimals: 6,
      symbol: 'USDC',
      name: 'USD Coin',
      metadata: { approved: true },
      // origin: 'stargate'
    }),
    new EvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0xcc1b99ddac1a33c201a742a1851662e87bc7f22c',
      decimals: 6,
      symbol: 'USDT',
      name: 'Tether USD',
      metadata: { approved: true },
      // origin: 'stargate'
    }),
    new EvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0x695921034f0387eac4e11620ee91b1b15a6a09fe',
      decimals: 18,
      symbol: 'WETH',
      name: 'Wrapped Ether',
      metadata: { approved: true },
      // origin: 'stargate'
    }),
    new EvmToken({
      chainId: EvmChainId.FANTOM,
      address: '0xf1648c50d2863f780c57849d812b4b7686031a3d',
      decimals: 18,
      symbol: 'WBTC',
      name: 'Wrapped BTC',
      metadata: { approved: true },
      // origin: 'stargate'
    }),
    axlUSDC[EvmChainId.FANTOM],
    MIM[EvmChainId.FANTOM],
  ],
  [EvmChainId.ARBITRUM]: [
    EvmNative.fromChainId(EvmChainId.ARBITRUM),
    WNATIVE[EvmChainId.ARBITRUM],
    ARB[EvmChainId.ARBITRUM],
    WBTC[EvmChainId.ARBITRUM],
    USDC[EvmChainId.ARBITRUM],
    USDT[EvmChainId.ARBITRUM],
    DAI[EvmChainId.ARBITRUM],
    MIM[EvmChainId.ARBITRUM],
  ],
  [EvmChainId.ARBITRUM_SEPOLIA]: [],
  [EvmChainId.HARMONY]: [
    EvmNative.fromChainId(EvmChainId.HARMONY),
    WNATIVE[EvmChainId.HARMONY],
    WETH9[EvmChainId.HARMONY],
    USDC[EvmChainId.HARMONY],
    USDT[EvmChainId.HARMONY],
    DAI[EvmChainId.HARMONY],
  ],
  [EvmChainId.CELO]: [
    EvmNative.fromChainId(EvmChainId.CELO),
    // WNATIVE[EvmChainId.CELO],
    WETH9[EvmChainId.CELO],
    USDC[EvmChainId.CELO],
    USDT[EvmChainId.CELO],
    DAI[EvmChainId.CELO],
  ],
  [EvmChainId.OPTIMISM]: [
    EvmNative.fromChainId(EvmChainId.OPTIMISM),
    WNATIVE[EvmChainId.OPTIMISM],
    WBTC[EvmChainId.OPTIMISM],
    USDC[EvmChainId.OPTIMISM],
    USDT[EvmChainId.OPTIMISM],
    DAI[EvmChainId.OPTIMISM],
  ],
  [EvmChainId.KAVA]: [
    EvmNative.fromChainId(EvmChainId.KAVA),
    WNATIVE[EvmChainId.KAVA],
    axlWBTC[EvmChainId.KAVA],
    new EvmToken({
      chainId: EvmChainId.KAVA,
      address: '0x2dfd4de5ae386cd3f4fc8e2cb39240852e47f5e8',
      decimals: 18,
      symbol: 'WETH',
      name: 'Wrapped Ether',
      metadata: { approved: true },
      // origin: 'stargate'
    }),
    axlUSDC[EvmChainId.KAVA],
    USDT[EvmChainId.KAVA],
  ],
  [EvmChainId.METIS]: [
    EvmNative.fromChainId(EvmChainId.METIS),
    WNATIVE[EvmChainId.METIS],
    WBTC[EvmChainId.METIS],
    WETH9[EvmChainId.METIS],
    USDC[EvmChainId.METIS],
    USDT[EvmChainId.METIS],
    DAI[EvmChainId.METIS],
  ],
  [EvmChainId.BOBA_BNB]: [
    EvmNative.fromChainId(EvmChainId.BOBA_BNB),
    WNATIVE[EvmChainId.BOBA_BNB],
    new EvmToken({
      chainId: EvmChainId.BOBA_BNB,
      symbol: 'BNB',
      name: 'Binance Coin',
      decimals: 18,
      address: '0x4200000000000000000000000000000000000023',
    }),
    USDC[EvmChainId.BOBA_BNB],
    USDT[EvmChainId.BOBA_BNB],
  ],
  [EvmChainId.BTTC]: [
    EvmNative.fromChainId(EvmChainId.BTTC),
    WNATIVE[EvmChainId.BTTC],
    WETH9[EvmChainId.BTTC],
    USDC[EvmChainId.BTTC],
    USDT[EvmChainId.BTTC],
  ],
  [EvmChainId.POLYGON_ZKEVM]: [
    EvmNative.fromChainId(EvmChainId.POLYGON_ZKEVM),
    WNATIVE[EvmChainId.POLYGON_ZKEVM],
    MATIC[EvmChainId.POLYGON_ZKEVM],
    USDC[EvmChainId.POLYGON_ZKEVM],
    USDT[EvmChainId.POLYGON_ZKEVM],
    DAI[EvmChainId.POLYGON_ZKEVM],
    WBTC[EvmChainId.POLYGON_ZKEVM],
  ],
  [EvmChainId.THUNDERCORE]: [
    EvmNative.fromChainId(EvmChainId.THUNDERCORE),
    WNATIVE[EvmChainId.THUNDERCORE],
    WETH9[EvmChainId.THUNDERCORE],
    USDC[EvmChainId.THUNDERCORE],
    USDT[EvmChainId.THUNDERCORE],
    WBTC[EvmChainId.THUNDERCORE],
  ],
  [EvmChainId.HAQQ]: [
    EvmNative.fromChainId(EvmChainId.HAQQ),
    WNATIVE[EvmChainId.HAQQ],
    axlETH[EvmChainId.HAQQ],
    axlWBTC[EvmChainId.HAQQ],
    axlUSDC[EvmChainId.HAQQ],
    axlUSDT[EvmChainId.HAQQ],
    axlDAI[EvmChainId.HAQQ],
  ],
  [EvmChainId.CORE]: [
    EvmNative.fromChainId(EvmChainId.CORE),
    WNATIVE[EvmChainId.CORE],
    WETH9[EvmChainId.CORE],
    USDC[EvmChainId.CORE],
    USDT[EvmChainId.CORE],
  ],
  [EvmChainId.ZKSYNC_ERA]: [
    EvmNative.fromChainId(EvmChainId.ZKSYNC_ERA),
    WNATIVE[EvmChainId.ZKSYNC_ERA],
    WBTC[EvmChainId.ZKSYNC_ERA],
    USDC[EvmChainId.ZKSYNC_ERA],
  ],
  [EvmChainId.LINEA]: [
    EvmNative.fromChainId(EvmChainId.LINEA),
    WNATIVE[EvmChainId.LINEA],
    DAI[EvmChainId.LINEA],
    USDC[EvmChainId.LINEA],
  ],
  [EvmChainId.BASE]: [
    EvmNative.fromChainId(EvmChainId.BASE),
    WNATIVE[EvmChainId.BASE],
    DAI[EvmChainId.BASE],
    new EvmToken({
      chainId: EvmChainId.BASE,
      symbol: 'USDbC',
      name: 'USD Base Coin',
      decimals: 6,
      address: '0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca',
      metadata: { approved: true },
    }),
    USDC[EvmChainId.BASE],
    new EvmToken({
      chainId: EvmChainId.BASE,
      symbol: 'OX',
      name: 'OX Coin',
      decimals: 18,
      address: '0xba0dda8762c24da9487f5fa026a9b64b695a07ea',
      metadata: { approved: true },
    }),
  ],
  [EvmChainId.SCROLL]: [
    EvmNative.fromChainId(EvmChainId.SCROLL),
    WNATIVE[EvmChainId.SCROLL],
    USDC[EvmChainId.SCROLL],
    USDT[EvmChainId.SCROLL],
    WBTC[EvmChainId.SCROLL],
  ],
  [EvmChainId.FILECOIN]: [
    EvmNative.fromChainId(EvmChainId.FILECOIN),
    WNATIVE[EvmChainId.FILECOIN],
    USDC[EvmChainId.FILECOIN],
    DAI[EvmChainId.FILECOIN],
  ],
  [EvmChainId.ZETACHAIN]: [
    EvmNative.fromChainId(EvmChainId.ZETACHAIN),
    WNATIVE[EvmChainId.ZETACHAIN],
    ZETA_USDC_ETH[EvmChainId.ZETACHAIN],
    ZETA_USDT_ETH[EvmChainId.ZETACHAIN],
    WETH9[EvmChainId.ZETACHAIN],
  ],
  [EvmChainId.CRONOS]: [
    EvmNative.fromChainId(EvmChainId.CRONOS),
    WNATIVE[EvmChainId.CRONOS],
    WETH9[EvmChainId.CRONOS],
    WBTC[EvmChainId.CRONOS],
    USDC[EvmChainId.CRONOS],
  ],
  [EvmChainId.BLAST]: [
    EvmNative.fromChainId(EvmChainId.BLAST),
    USDB[EvmChainId.BLAST],
  ],
  [EvmChainId.SKALE_EUROPA]: [
    SKL[EvmChainId.SKALE_EUROPA],
    USDC[EvmChainId.SKALE_EUROPA],
    WETH9[EvmChainId.SKALE_EUROPA],
  ],
  [EvmChainId.ROOTSTOCK]: [
    EvmNative.fromChainId(EvmChainId.ROOTSTOCK),
    WNATIVE[EvmChainId.ROOTSTOCK],
    USDT0[EvmChainId.ROOTSTOCK],
    new EvmToken({
      chainId: EvmChainId.ROOTSTOCK,
      address: '0x1d931bf8656d795e50ef6d639562c5bd8ac2b78f',
      decimals: 18,
      symbol: 'ETHs',
      name: 'ETHs',
    }),
    SolvBTC[EvmChainId.ROOTSTOCK],
    USDT[EvmChainId.ROOTSTOCK],
    RBTC[EvmChainId.ROOTSTOCK],
  ],
  [EvmChainId.MANTLE]: [
    EvmNative.fromChainId(EvmChainId.MANTLE),
    WNATIVE[EvmChainId.MANTLE],
    WETH9[EvmChainId.MANTLE],
    USDC[EvmChainId.MANTLE],
  ],
  [EvmChainId.MANTA]: [
    EvmNative.fromChainId(EvmChainId.MANTA),
    WNATIVE[EvmChainId.MANTA],
    USDC[EvmChainId.MANTA],
    USDT[EvmChainId.MANTA],
    WBTC[EvmChainId.MANTA],
  ],
  [EvmChainId.MODE]: [
    EvmNative.fromChainId(EvmChainId.MODE),
    WNATIVE[EvmChainId.MODE],
    USDC[EvmChainId.MODE],
    USDT[EvmChainId.MODE],
    WBTC[EvmChainId.MODE],
  ],
  [EvmChainId.TAIKO]: [
    EvmNative.fromChainId(EvmChainId.TAIKO),
    WNATIVE[EvmChainId.TAIKO],
    USDC[EvmChainId.TAIKO],
    USDT[EvmChainId.TAIKO],
    DAI[EvmChainId.TAIKO],
    WBTC[EvmChainId.TAIKO],
  ],
  [EvmChainId.ZKLINK]: [
    EvmNative.fromChainId(EvmChainId.ZKLINK),
    WNATIVE[EvmChainId.ZKLINK],
    USDC[EvmChainId.ZKLINK],
    USDT[EvmChainId.ZKLINK],
    DAI[EvmChainId.ZKLINK],
    WBTC[EvmChainId.ZKLINK],
  ],
  [EvmChainId.APE]: [
    EvmNative.fromChainId(EvmChainId.APE),
    WNATIVE[EvmChainId.APE],
    APE_USD[EvmChainId.APE],
  ],
  [EvmChainId.SONIC]: [
    EvmNative.fromChainId(EvmChainId.SONIC),
    WNATIVE[EvmChainId.SONIC],
    USDC[EvmChainId.SONIC],
    WETH9[EvmChainId.SONIC],
  ],
  [EvmChainId.HEMI]: [
    EvmNative.fromChainId(EvmChainId.HEMI),
    WNATIVE[EvmChainId.HEMI],
    USDC[EvmChainId.HEMI],
    USDT[EvmChainId.HEMI],
  ],
  [EvmChainId.TATARA]: [
    EvmNative.fromChainId(EvmChainId.TATARA),
    WNATIVE[EvmChainId.TATARA],
    AUSD[EvmChainId.TATARA],
  ],
  [EvmChainId.KATANA]: [
    EvmNative.fromChainId(EvmChainId.KATANA),
    WNATIVE[EvmChainId.KATANA],
    USDC[EvmChainId.KATANA],
    USDT[EvmChainId.KATANA],
    AUSD[EvmChainId.KATANA],
  ],
  [EvmChainId.HYPEREVM]: [
    EvmNative.fromChainId(EvmChainId.HYPEREVM),
    WNATIVE[EvmChainId.HYPEREVM],
    USDT[EvmChainId.HYPEREVM],
  ],
  [EvmChainId.BERACHAIN]: [
    EvmNative.fromChainId(EvmChainId.BERACHAIN),
    WNATIVE[EvmChainId.BERACHAIN],
    USDT[EvmChainId.BERACHAIN],
  ],
} as const satisfies Record<EvmChainId, Readonly<EvmCurrency[]>>
