name: "Install"
description: "Install dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.27.0
